import type { Metadata } from "next";
import Link from "next/link";
import { PreferencesButton } from "@/components/experience/entry";
export const metadata: Metadata = { title: "Privacy", description: "Contact, research assistance, optional analytics and privacy choices.", alternates: { canonical: "/privacy" } };
export default function Privacy() {
  return <main id="main" tabIndex={-1} className="shell legal-page"><Link className="back-link" href="/">← Home</Link><p className="eyebrow">PRIVACY</p><h1>Your inquiry, handled with care.</h1><p className="legal-intro">Michael P. Gibb’s portfolio uses information to answer inquiries, provide optional research assistance and improve the website. Optional analytics and replay remain off unless enabled and you choose them.</p>
    <section><h2>Your choices</h2><p>You can browse, use the assistant and contact Michael without agreeing to analytics. Analytics and masked session replay have separate choices; replay requires analytics. Accepting analytics alone does not enable replay. Browser Do Not Track and Global Privacy Control also suppress optional measurement. <PreferencesButton /></p><p>A signed preference cookie records your choices for up to 180 days. With analytics consent, it also carries random browser and session identifiers and controlled referral categories. With rejection, it contains no behavioral identifiers. Withdrawal stops capture, clears optional browser identifiers and prevents new events under the withdrawn browser identifier. Previously collected data may remain until expiry or deletion.</p></section>
    <section><h2>Contact inquiries</h2><p>Name, email address and message are required. Organization, phone, role and timeline are optional. The ordinary form and assistant inquiry preview use the same protected delivery service. Only the message you review and explicitly send, supplied contact details and selected project references enter the inquiry; the chat transcript is not attached.</p><p>Vercel processes requests, Resend handles outbound delivery, and Porkbun hosts the designated mailbox. Application inquiry records are encrypted in Upstash Redis and expire after 90 days by default. The owner inbox requires server-verified GitHub authentication restricted to the owner account. Access is not granted by knowing a link. Inquiry emails and correspondence in the mailbox require separate retention and deletion review.</p><p>Application receipt, provider acceptance and verified delivery or bounce are different statuses. A successful submission means the email service accepted the inquiry. Signed delivery webhooks, when configured, can confirm delivery to the receiving mail server, not inbox placement or reading.</p></section>
    <section><h2>AI research assistance</h2><p>When activated, the AI assistant sends your question, a small amount of temporary conversation context and retrieved public portfolio evidence to OpenAI’s Responses API. It is an AI assistant, not Michael responding live. Do not include confidential records or sensitive personal information. Answers can be mistaken; consult their source links.</p><p>Conversation context is encrypted in Upstash and expires with the security session within 15 minutes. No optional saved-transcript feature is enabled. The API requests no stored response object (<code>store: false</code>); OpenAI may retain safety and operational records under its own data policies. This setting does not promise zero provider retention. Closing the panel cancels an active request but does not erase records already processed by a provider.</p></section>
    <section><h2>Essential security</h2><p>Cloudflare Turnstile verifies contact submissions and the first request of a chat session. Reading pages or opening the panel alone does not trigger a challenge. Managed verification may complete without an interactive puzzle. A short-lived Secure, HttpOnly chat cookie expires after 15 minutes. Server-side limits apply to every request across instances.</p><p>Upstash retains keyed hashes of network addresses, single-use tokens and submission identifiers, counters and deduplication receipts. Token hashes expire after 310 seconds; security counters and duplicate receipts expire within one day. No raw IP addresses, tokens, message contents or secrets enter application security logs. A failed challenge is an outcome, not a confirmed bot classification. Aggregate model usage, estimated cost, failure counts and latency are essential operational records, retained for 30 days without visitor identifiers.</p><p>These services work independently of analytics consent. Hosting, verification and email providers may process network metadata or retain logs under their respective policies.</p></section>
    <section><h2>Optional analytics and journeys</h2><p>When activated and accepted, PostHog receives allowlisted events: public page paths, project IDs, broad search intents, interaction categories, device/browser categories, country where available, timing and delivery outcomes. It does not receive raw search terms, chat text, inquiry text, names, email addresses, arbitrary URL queries or fragments. Country uses hosting metadata; raw IP addresses are excluded from the analytics payload and location enrichment is disabled.</p><p>Random identifiers represent browsers and sessions, not verified people. They do not prove identity or employer. Sending a contact form is not a login and does not merge unrelated histories. The private inquiry record may include the available consented session sequence and controlled referral/campaign categories. Missing attribution stays unknown. Analytics can undercount because of rejection, blockers, exclusions or usage limits.</p><p>Local journey records expire after 30 days; snapshots linked to an inquiry expire with that inquiry. Activation requires PostHog event retention of 90 days. The owner can export private inquiry records and request deletion of linked PostHog events and recordings. Provider event deletion is asynchronous and must be checked for completion.</p></section>
    <section><h2>Optional masked replay</h2><p>Replay is disabled until separately configured and verified. With your separate permission, eligible sessions may be sampled at up to 10%, with at most 10 recording sessions a day. Inputs, visible text and element attributes are masked; contact forms, chat transcripts, inquiry previews and private pages are excluded. Request/response bodies, sensitive headers and console logs are not recorded. Activation requires a 30-day replay retention setting. Masking reduces visual detail; heatmaps and frustration indicators describe interactions, not intent.</p></section>
    <section><h2>Privacy assistance and providers</h2><p>Request access, correction or deletion through the <Link href="/#contact">contact form</Link>. Please identify the inquiry sufficiently to locate it without sending unnecessary personal information. Deletion covers the retained application record and linked analytics where held; mailbox and provider records require separate review.</p><p>Read the provider policies: <a href="https://vercel.com/legal/privacy-policy">Vercel</a>, <a href="https://resend.com/legal/privacy-policy">Resend</a>, <a href="https://upstash.com/trust/privacy.pdf">Upstash</a>, <a href="https://www.cloudflare.com/privacypolicy/">Cloudflare</a>, <a href="https://openai.com/policies/privacy-policy/">OpenAI</a>, <a href="https://posthog.com/privacy">PostHog</a>, <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">GitHub</a> and <a href="https://porkbun.com/legal/privacy">Porkbun</a>. External links operate under those sites’ policies.</p></section>
  </main>;
}
