import type { Metadata } from "next";
import Link from "next/link";
export const metadata: Metadata = { title: "Privacy", description: "How this portfolio handles contact inquiries and technical information.", alternates: { canonical: "/privacy" } };
export default function Privacy() {
  return <main id="main" tabIndex={-1} className="shell legal-page"><Link className="back-link" href="/">← Home</Link><p className="eyebrow">PRIVACY</p><h1>Your inquiry, handled with care.</h1><p className="legal-intro">This page explains the information used by Michael P. Gibb’s professional portfolio and its contact form.</p>
    <section><h2>Information you submit</h2><p>The form asks for your full name, email address and message. Company or organization, phone number and discussion topic are optional. These details are used to review and respond to your inquiry. Please include only information appropriate for an initial professional conversation; do not send confidential records or sensitive personal information.</p></section>
    <section><h2>Delivery and service providers</h2><p>Vercel hosts the website and processes form requests. Resend processes the message for email delivery to Michael’s designated mailbox. The destination email provider and mailbox may retain the message and related correspondence. Sending a message does not subscribe you to marketing, and the form sends no automatic reply to your address.</p><p>A successful form response means the email service accepted the message for delivery. It does not independently confirm that the message reached the inbox or was read.</p></section>
    <section><h2>Spam protection and technical information</h2><p>The server validates submissions, checks a hidden spam-trap field, and limits submission attempts. An Upstash Redis store holds keyed hashes of network addresses and submission identifiers, counters, timestamps and random delivery tokens. The application does not put message text, names or contact details in that store. Rate-limit counters expire after one hour or one day; duplicate-prevention records expire after one day.</p><p>The application logs only generic delivery or storage failure events, without message contents or contact details. Hosting, email and security providers may keep request metadata, network addresses, delivery records and operational logs under their own policies and account settings.</p></section>
    <section><h2>Cookies, analytics and browser storage</h2><p>This portfolio does not load a visitor-analytics or advertising script and does not set application cookies for tracking. Research filter choices appear in the page URL so a selection can be shared. Form entries remain in the current page while it is open and are preserved after a failed submission; the application does not save them in browser local storage.</p><p>External websites, including LinkedIn and linked research sources, operate under their own privacy practices.</p></section>
    <section><h2>Retention and privacy assistance</h2><p>Inquiry emails and correspondence may be retained as needed to handle the discussion and related professional records. No fixed deletion period is promised for mailboxes or provider logs. You can request information, correction or deletion of your inquiry through the <Link href="/#contact">contact form</Link>; requests will be considered in light of the information held and any applicable obligations.</p><p>Provider details: <a href="https://vercel.com/legal/privacy-policy">Vercel privacy policy</a>, <a href="https://resend.com/legal/privacy-policy">Resend privacy policy</a> and <a href="https://upstash.com/trust/privacy.pdf">Upstash privacy policy</a>.</p></section>
  </main>;
}
