"use client";
import { useState } from "react";
import type { AdvertisingFrontier } from "@/lib/advertising-results";
const money=(x:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2}).format(x);
export function AdvertisingEvidence({frontier,models,principal}:{frontier:AdvertisingFrontier[];models:{id:string;label:string}[];principal:string}){
 const capacities=[0,.01,.05,.1,.2,.3,.5,.75,1];const [index,setIndex]=useState(4);const [model,setModel]=useState(principal);const [value,setValue]=useState(100);const [cost,setCost]=useState(.1);const capacity=capacities[index];
 const points=frontier.filter(x=>x.model===model);const row=points.find(x=>x.capacity===capacity)!;const response=frontier.filter(x=>x.model==="response");const random=frontier.filter(x=>x.model==="random");const visible=[...points,...response,...random];const min=Math.min(0,...visible.map(x=>x.lower));const max=Math.max(1,...visible.map(x=>x.upper));const py=(y:number)=>260-(y-min)/(max-min)*205;const px=(x:number)=>80+535*x;
 const line=(rows:AdvertisingFrontier[])=>rows.map(x=>`${px(x.capacity)},${py(x.estimate)}`).join(" ");const band=[...points.map(x=>`${px(x.capacity)},${py(x.upper)}`),...points.toReversed().map(x=>`${px(x.capacity)},${py(x.lower)}`)].join(" ");
 const scenario=(x:number)=>x*value-row.selected_fraction*10000*cost;
 function reset(){setIndex(4);setModel(principal);setValue(100);setCost(.1);}
 return <div className="program-explorer" data-testid="advertising-evidence"><div className="explorer-heading"><div><p className="eyebrow">ADVERTISING CAPACITY EXPLORER</p><h3>Does a different ranking earn the same budget?</h3></div><button type="button" className="catalog-reset" onClick={reset}>Reset advertising comparison</button></div><p>These are saved independent evaluation scores. Capacity changes the frozen ranking’s selection; it does not refit the model or observe a new experiment.</p><div className="program-controls"><label>Targeting policy<select value={model} onChange={e=>setModel(e.target.value)}>{models.map(x=><option key={x.id} value={x.id}>{x.label}{x.id===principal?" · selected in validation":""}</option>)}</select></label><label>Targeting capacity: {Math.round(capacity*100)}%<input aria-label="Targeting capacity" aria-valuetext={`${Math.round(capacity*100)}% of eligible records`} type="range" min="0" max="8" step="1" value={index} onChange={e=>setIndex(Number(e.target.value))}/><span className="caption">Saved points: 0, 1, 5, 10, 20, 30, 50, 75 and 100%.</span></label></div><div className="executive-stats" aria-live="polite"><div><strong>{row.estimate.toFixed(2)}</strong><span>benchmark conversions per 10,000</span></div><div><strong>{row.lower.toFixed(2)} to {row.upper.toFixed(2)}</strong><span>conditional 95% interval</span></div><div><strong>{row.selected.toLocaleString("en-US",{maximumFractionDigits:1})}</strong><span>{model==="random"?"expected selected records":"selected evaluation records"}</span></div></div><p className="caption">Conversion estimates are incremental benchmark contrasts relative to no targeting, under the study’s identification assumptions. They are not observed counts of caused conversions or original advertiser effects.</p>
 <figure className="capacity-chart inventory-chart" tabIndex={0}><svg viewBox="0 0 660 320" role="img" aria-labelledby="advertising-frontier-title advertising-frontier-desc"><title id="advertising-frontier-title">Independent policy contrast across targeting capacities</title><desc id="advertising-frontier-desc">Selected policy and its conditional 95% band, response targeting and expected random targeting. Exact comparisons at the selected capacity follow.</desc>{[0,.25,.5,.75,1].map(f=><g key={f}><line x1="80" x2="615" y1={py(min+f*(max-min))} y2={py(min+f*(max-min))} className="chart-grid"/><text x="70" y={py(min+f*(max-min))+4} textAnchor="end">{(min+f*(max-min)).toFixed(1)}</text><text x={px(f)} y="283" textAnchor="middle">{Math.round(f*100)}%</text></g>)}<polygon points={band} fill="#925322" opacity=".12"/><polyline points={line(random)} className="chart-random"/><polyline points={line(response)} fill="none" stroke="#0a192f" strokeWidth="2"/><polyline points={line(points)} className="chart-policy"/><circle cx={px(capacity)} cy={py(row.estimate)} r="6" className="chart-selected"/><text x="80" y="24">Benchmark conversions per 10,000 eligible records</text><text x="350" y="314" textAnchor="middle">Targeting capacity (%)</text></svg><figcaption>Copper and shaded band: selected policy. Navy: response targeting. Dashed slate: expected random allocation. Intervals are conditional and not simultaneous across the frontier. Scroll horizontally on narrow screens.</figcaption></figure>
 <div className="program-table-wrap" tabIndex={0} role="region" aria-label="Advertising policies at selected capacity"><table><caption>All policies · {Math.round(capacity*100)}% capacity</caption><thead><tr><th scope="col">Policy</th><th scope="col">Contrast / 10,000</th><th scope="col">95% interval</th></tr></thead><tbody>{frontier.filter(x=>x.capacity===capacity).map(x=><tr key={x.model}><th scope="row">{models.find(m=>m.id===x.model)!.label}</th><td>{x.estimate.toFixed(2)}</td><td>{x.lower.toFixed(2)} to {x.upper.toFixed(2)}</td></tr>)}</tbody></table></div><p>At 0%, every policy targets nobody and its contrast is zero. At 100%, all policies target everyone and share the same estimate. The primary model decision was fixed at 20%; the other capacity points are supplementary.</p>
 <div className="scenario-panel"><p className="eyebrow">ASSUMED ECONOMICS / SCENARIO ONLY</p><h3>Translate the benchmark into an explicit assumption.</h3><p>Neither conversion value nor contact cost is observed. This calculation is a benchmark illustration, not original advertiser ROI or profit.</p><div className="program-controls"><label>Assumed value per incremental conversion: {money(value)}<input aria-label="Assumed conversion value" aria-valuetext={`${money(value)} per incremental conversion`} type="range" min="0" max="1000" step="10" value={value} onChange={e=>setValue(Number(e.target.value))}/><span className="caption">$0–$1,000 per conversion</span></label><label>Assumed cost per targeted record: {money(cost)}<input aria-label="Assumed targeting cost" aria-valuetext={`${money(cost)} per targeted record`} type="range" min="0" max="10" step="0.05" value={cost} onChange={e=>setCost(Number(e.target.value))}/><span className="caption">$0–$10 per targeted record</span></label></div><p className="scenario-value" aria-live="polite">{money(scenario(row.estimate))} <span>illustrative net value per 10,000 eligible records</span></p><p>Conditional scenario range: {money(scenario(row.lower))} to {money(scenario(row.upper))}. Negative values indicate assumed cost exceeds the estimated benchmark value at these inputs.</p><p className="caption">Calculation: benchmark conversion contrast × assumed value − selected fraction × 10,000 × assumed targeting cost. Fixed-price intervals exclude uncertainty in economics, privacy sampling, future populations and model refitting.</p></div></div>;
}
