"use client";

import { useState } from "react";
import type { ContactFrontier } from "@/lib/program-results";

const percent = (value: number) => `${(100 * value).toFixed(1)}%`;
const money = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value);
export function ContactPriorityEvidence({ frontier, models }: { frontier: ContactFrontier[]; models: { id: string; label: string }[] }) {
  const [capacity, setCapacity] = useState(.2);
  const [model, setModel] = useState("business_rule");
  const [cost, setCost] = useState(10);
  const [value, setValue] = useState(100);
  const rows = frontier.filter(row => row.capacity === capacity);
  const selected = rows.find(row => row.model === model)!;
  const points = frontier.filter(row => row.model === model);
  const net = selected.responses * value - selected.selected * cost;
  const scenarioBound = (precision: number) => selected.selected * (precision * value - cost);
  function reset() { setCapacity(.2); setModel("business_rule"); setCost(10); setValue(100); }
  return <div className="program-explorer" data-testid="contact-priority-evidence">
    <div className="explorer-heading"><div><p className="eyebrow">CONTACT CAPACITY EXPLORER</p><h3>Which recorded responses would the ranking capture?</h3></div><button type="button" className="catalog-reset" onClick={reset}>Reset comparison</button></div>
    <p>Choose a saved model and capacity. The chart and counts use the untouched historical holdout; controls do not retrain models or change their measured accuracy.</p>
    <div className="program-controls"><label>Ranking model<select value={model} onChange={event => setModel(event.target.value)}>{models.map(item => <option value={item.id} key={item.id}>{item.label}</option>)}</select></label><label>Contact capacity<select value={capacity} onChange={event => setCapacity(Number(event.target.value))}>{points.map(point => <option key={point.capacity} value={point.capacity}>{Math.round(point.capacity * 100)}% of final cohort</option>)}</select></label></div>
    <div className="executive-stats" aria-live="polite"><div><strong>{selected.selected.toLocaleString("en-US")}</strong><span>contacts selected</span></div><div><strong>{selected.responses.toLocaleString("en-US", {maximumFractionDigits: 1})}</strong><span>{model === "random" ? "expected recorded responses" : "recorded responses in selection"}</span></div><div><strong>{percent(selected.precision)}</strong><span>response precision</span></div></div>
    <p className="caption">Conditional 95% precision interval: {percent(selected.precision_interval.lower)}–{percent(selected.precision_interval.upper)}. Captures {percent(selected.capture)} of recorded subscriptions; interval {percent(selected.capture_interval.lower)}–{percent(selected.capture_interval.upper)}. Intervals describe resampling uncertainty, not uncertainty about already observed counts.</p>
    <figure className="capacity-chart"><svg role="img" aria-labelledby="capacity-title capacity-desc" viewBox="0 0 660 330"><title id="capacity-title">Capacity and captured recorded subscriptions</title><desc id="capacity-desc">The selected ranking is compared with random allocation. The table provides exact results at the chosen capacity.</desc>{[0,25,50,75,100].map(tick => <g key={tick}><line x1="65" x2="625" y1={275 - tick * 2.2} y2={275 - tick * 2.2} className="chart-grid"/><text x="52" y={279 - tick * 2.2} textAnchor="end">{tick}%</text><text x={65 + tick * 5.6} y="298" textAnchor="middle">{tick}%</text></g>)}<path d="M65 275 L625 55" className="chart-random"/><polyline className="chart-policy" points={points.map(point => `${65+point.capacity*560},${275-point.capture*220}`).join(" ")}/><circle cx={65+capacity*560} cy={275-selected.capture*220} r="6" className="chart-selected"/><text x="345" y="324" textAnchor="middle">Contact capacity (% of holdout)</text><text x="65" y="25">Captured recorded subscriptions (%)</text></svg><figcaption>Copper: selected ranking. Dashed slate: expected random allocation. No effect of calling is identified.</figcaption></figure>
    <div className="program-table-wrap" tabIndex={0} role="region" aria-label="All model results at chosen contact capacity"><table><caption>Model comparison at {Math.round(capacity*100)}% contact capacity</caption><thead><tr><th scope="col">Model</th><th scope="col">Responses</th><th scope="col">Precision</th><th scope="col">Captured</th></tr></thead><tbody>{rows.map(row => <tr key={row.model}><th scope="row">{models.find(item => item.id === row.model)!.label}</th><td>{row.responses.toLocaleString("en-US", {maximumFractionDigits: 1})}{row.model === "random" ? " expected" : ""}</td><td>{percent(row.precision)}</td><td>{percent(row.capture)}</td></tr>)}</tbody></table></div>
    <div className="scenario-panel"><p className="eyebrow">ASSUMED ECONOMICS / SCENARIO ONLY</p><h3>What would these counts imply under your assumptions?</h3><p>Hypothetical USD-equivalent units; neither cost nor response value is observed in the data. No incremental profit is estimated.</p><div className="program-controls"><label>Assumed cost per contact: {money(cost)}<input type="range" min="0" max="50" step="1" value={cost} onChange={event=>setCost(Number(event.target.value))}/><span className="caption">Supported range: $0–$50</span></label><label>Assumed value per response: {money(value)}<input type="range" min="0" max="1000" step="10" value={value} onChange={event=>setValue(Number(event.target.value))}/><span className="caption">Supported range: $0–$1,000</span></label></div><p className="scenario-value" aria-live="polite">{money(net)} <span>illustrative value less contact cost</span></p><p>Conditional scenario range: {money(scenarioBound(selected.precision_interval.lower))}–{money(scenarioBound(selected.precision_interval.upper))}. Assumed break-even response value: {money(cost / selected.precision)}.</p><p className="caption">Calculation: selected responses × assumed response value − selected contacts × assumed contact cost. Range rescales the conditional precision interval at the selected count. It excludes retraining, future population shifts and uncertainty in your economic assumptions.</p></div>
  </div>;
}
