import { CaseContents } from "@/components/case-contents";
import { StudyNextSteps } from "@/components/study-next-steps";
import Link from "next/link";
import { Footer } from "@/components/portfolio";
import { ContactPriorityEvidence } from "@/components/contact-priority-evidence";
import type { ProgramStudy } from "@/lib/program-registry";
import { contactResult as result, percent } from "@/lib/program-results";
import { productionOrigin } from "@/lib/site";
export function ContactStudy({ study }: { study: ProgramStudy }) {
  const delta = result.tables.block_sensitivity[0];
  const selected = result.tables.capacity_frontier.find(row => row.model === "business_rule" && row.capacity === .2)!;
  const challenger = result.tables.capacity_frontier.find(row => row.model === result.tables.selected_model && row.capacity === .2)!;
  const code = `https://github.com/mpgibb/michael-gibb-research/tree/${result.code_version}/studies/S28`;
  const report = "https://github.com/mpgibb/michael-gibb-research/blob/main/studies/S28/REPORT.md";
  const structured = { "@context": "https://schema.org", "@type": "ScholarlyArticle", headline: study.title, author: { "@type": "Person", name: "Michael P. Gibb, Ph.D." }, url: `${productionOrigin}/research/${study.slug}`, about: "Historical sales-contact response prediction", datePublished: result.evaluated_on, citation: result.data.source_url, isAccessibleForFree: true };
  return <><main id="main" tabIndex={-1}>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structured).replace(/</g,"\\u003c") }}/>
    <section className="project-hero program-hero"><div className="shell"><Link className="back-link" href="/research">← Research catalog</Link><p className="eyebrow">S28 / SALES CONTACT PRIORITIZATION</p><h1>Earn the case for a more complex contact model.</h1><p className="project-question">At 20% contact capacity, the simple history rule identifies {selected.responses} recorded subscriptions versus {challenger.responses} for the model selected during development.</p><div className="project-hero-foot"><span className="status-light">Evaluated public-data study</span><a className="button-light" href={code}>Research code ↗</a><a className="button-light" href="#decision">Executive summary ↓</a></div><p className="program-coverage">41,188 records · UCI Bank Marketing · May 2008–November 2010 · 8,238 final-test contacts</p></div></section>
    <div className="shell case-layout"><CaseContents /><article className="case-body">
      <section id="decision" className="executive-summary"><p className="eyebrow">01 / DECISION · EXECUTIVE SUMMARY</p><h2>Keep the simple benchmark until the upgrade proves itself.</h2><p className="reading">A sales leader with limited calling capacity needs a reliable way to prioritize contacts. In this historical bank dataset, the rule based on previous campaign success and contact history performs better than the logistic model selected on earlier records. Greater model complexity does not earn its place in this test.</p><div className="executive-stats"><div><strong>{selected.responses}</strong><span>subscriptions identified by the rule</span></div><div><strong>{challenger.responses}</strong><span>identified by the selected model</span></div><div><strong>{selected.selected.toLocaleString("en-US")}</strong><span>contacts selected by each policy</span></div></div><div className="executive-takeaway"><h3>What a leader should do next</h3><p>Use the rule as a benchmark in a current, controlled validation. Require a replacement to improve both forecast quality and the decision at the actual contact capacity. Monitor changing response rates before scaling.</p></div><div className="executive-caution"><h3>What this does not establish</h3><p>Every record comes from an observed campaign contact. The study predicts recorded response; it cannot tell how many subscriptions the call caused. There is no measured profit or current-client outcome. The historical record sequence also lacks exact dates and customer identifiers.</p></div><a className="text-link explorer-shortcut" href="#interactive-results">Explore the interactive results ↓</a></section>
      <section id="implication"><p className="eyebrow">02 / IMPLICATION</p><h2>A better ranking score is not the whole decision.</h2><p className="reading">The selected logistic model has a higher AUROC than the rule, yet identifies fewer subscriptions at the specified capacity and has worse probability forecasts. Compare the metric that serves the decision, and keep adverse findings visible.</p><p>The primary log-loss difference (selected model minus rule) is <strong>{delta.estimate.toFixed(4)} natural-log units</strong>, with a 95% interval of <strong>{delta.lower.toFixed(4)}–{delta.upper.toFixed(4)}</strong>. Positive values favor the simpler rule. This advantage persists across the prespecified bootstrap block-size checks.</p></section>
      <section id="evidence"><p className="eyebrow">03 / EVIDENCE</p><h2>Measured comparisons, explicit assumptions.</h2><p>Final holdout: {result.samples.test.toLocaleString("en-US")} source-ordered contacts and {result.samples.events.test.toLocaleString("en-US")} subscriptions. Primary metric: log loss, which penalizes confident wrong probabilities; lower is better.</p><div className="program-table-wrap" tabIndex={0} role="region" aria-label="Held-out probability quality"><table><caption>Untouched final holdout · all prespecified models</caption><thead><tr><th scope="col">Model</th><th scope="col">Log loss</th><th scope="col">95% interval</th><th scope="col">AUROC</th></tr></thead><tbody>{result.models.map(model=>{const loss=result.metrics.find(metric=>metric.model===model.id&&metric.name==="log_loss")!;const auc=result.metrics.find(metric=>metric.model===model.id&&metric.name==="auroc")!;return <tr key={model.id}><th scope="row">{model.label}{model.id===result.tables.selected_model ? " · selected in development" : ""}</th><td>{loss.estimate.toFixed(4)}</td><td>{loss.lower.toFixed(4)}–{loss.upper.toFixed(4)}</td><td>{auc.estimate.toFixed(3)}</td></tr>;})}</tbody></table></div><p className="caption">Richer-attribute boosting is a sensitivity analysis. Random allocation uses the preceding calibration cohort’s response rate for its constant probability forecast. All models were fixed before final scoring.</p><ContactPriorityEvidence frontier={result.tables.capacity_frontier} models={result.models}/>
      <details><summary>Chronological failure groups and probability calibration</summary><p>These are four consecutive groups of final source rows, not calendar quarters. Response rates shift substantially; earlier calibration does not protect against later change.</p><div className="program-table-wrap" tabIndex={0} role="region" aria-label="Chronological diagnostics"><table><caption>Simple rule and selected model across final-test subperiods</caption><thead><tr><th scope="col">Group</th><th scope="col">Contacts</th><th scope="col">Response rate</th><th scope="col">Rule loss</th><th scope="col">Model loss</th></tr></thead><tbody>{result.tables.periods.filter(row=>row.model==="business_rule").map(row=><tr key={row.period}><th scope="row">{row.period}</th><td>{row.n}</td><td>{percent(row.events/row.n)}</td><td>{row.log_loss.toFixed(4)}</td><td>{result.tables.periods.find(other=>other.model===result.tables.selected_model&&other.period===row.period)!.log_loss.toFixed(4)}</td></tr>)}</tbody></table></div><div className="program-table-wrap" tabIndex={0} role="region" aria-label="Selected model calibration"><table><caption>Selected model · occupied probability bins</caption><thead><tr><th scope="col">Contacts</th><th scope="col">Mean forecast</th><th scope="col">Observed rate</th></tr></thead><tbody>{result.tables.calibration.filter(row=>row.model===result.tables.selected_model).map((row,i)=><tr key={i}><td>{row.n}</td><td>{percent(row.prediction)}</td><td>{percent(row.observed)}</td></tr>)}</tbody></table></div><p>Adding demographic and loan/default attributes does not reverse the primary conclusion. Removing two test profiles seen in earlier data also leaves the comparison intact. Matching anonymized profiles do not prove matching people. <a href={report}>Full diagnostics and sensitivity report ↗</a></p></details><p className="caption">{result.uncertainty} These intervals do not remove dependence from unidentified repeated customers or include model-retraining uncertainty.</p></section>
      <section id="data"><p className="eyebrow">04 / DATA</p><h2>Historical contacts, with a strict pre-call cutoff.</h2><p className="reading">{result.data.citation}. The full bank-additional file contains {result.samples.total.toLocaleString("en-US")} rows, ordered by date by its publisher. Coverage is May 2008–November 2010; exact per-call dates and stable customer IDs are unavailable.</p><p>Development uses the first {result.samples.train.toLocaleString("en-US")} rows; probability calibration uses the next {result.samples.calibration.toLocaleString("en-US")}; evaluation uses the final {result.samples.test.toLocaleString("en-US")}. There are 12 exact repeated rows, two final profiles seen in earlier records, and 570 final contacts with a month category not seen in development. Missing categories remain explicit.</p><p>Call duration is excluded because it is unavailable before the call. All five economic indicators are excluded because their historical release vintages cannot be verified. Current-campaign call count is reduced by one to exclude the current call.</p><p><a className="text-link" href={result.data.source_url}>Publisher, data and CC BY 4.0 terms ↗</a></p><p className="caption">No individual contact records are published here. Aggregate exports retain data/source hashes and the observed sampling boundaries.</p></section>
      <section id="method"><p className="eyebrow">05 / METHOD & LIMITATIONS</p><h2>Chronological evaluation before model preference.</h2><p className="reading">Two expanding development folds choose regularization or tree complexity using log loss. Logistic regression, additive splines and histogram gradient boosting train on the first 70% of records. A disjoint next 10% fits sigmoid probability calibration. The last 20% is untouched until evaluation.</p><p>The principal family is selected only from development results. All candidates remain in the final comparison. The simple rule prioritizes previous success, prior contact, recency and fewer earlier calls. The primary model uses operational contact history; a separate richer-feature sensitivity adds demographic and loan attributes.</p><ul className="evaluation-list">{result.limitations.map(limit=><li key={limit}>{limit}</li>)}</ul><p>At 20% capacity the rule’s precision is {percent(selected.precision)}, with a conditional 95% interval of {percent(selected.precision_interval.lower)}–{percent(selected.precision_interval.upper)}. Decision intervals resample the frozen selected indicators; resampled selection counts may vary. They are not causal intervals or guarantees for a new campaign.</p><p><a className="text-link" href={`${code}/PROTOCOL.md`}>Frozen protocol and feature definitions ↗</a></p></section>
      <section id="code"><p className="eyebrow">06 / CODE</p><h2>Follow the finding back to the run.</h2><p className="mono program-run">Run {result.run_id}<br/>Analysis commit {result.code_version}</p><pre><code>{`git clone https://github.com/mpgibb/michael-gibb-research.git\ncd michael-gibb-research\nuv sync --frozen\nuv run python -W error -m unittest discover -s tests -v\nuv run python -W error studies/S28/study.py\nuv run python scripts/report_s28.py`}</code></pre><div className="project-links"><a className="text-link" href={study.codeUrl!}>Study source & documentation ↗</a><a className="text-link" href={code}>Exact evaluated analysis ↗</a><a className="text-link" href={report}>Full report ↗</a><a className="text-link" href="/downloads/research/S28.json">Aggregate results JSON ↓</a></div><p className="caption">Python 3.11.16 · locked dependencies · fixed seeds · 15 correctness checks. Source and CSV checksums are included in the result export. Independent technical review is pending.</p></section>
    <StudyNextSteps id={study.id} /></article></div>
  </main><Footer/></>;
}
