"use client";
import { ModelSelect } from "@/components/model-select";
import { formatCurrency, formatPercent } from "@/lib/format";
import { useState } from "react";
import type { CustomerReturnProfile } from "@/lib/customer-return-results";
const gbp = (value: number, digits = 2) => formatCurrency(value, digits, "GBP");
const pct = formatPercent;
const inactivityOptions=["All inactivity bands","0–30 days","31–90 days","Over 90 days"];
const frequencyOptions=["All purchase histories","One purchase day","2–5 purchase days","6+ purchase days"];
export function CustomerReturnEvidence({profiles,models}:{profiles:CustomerReturnProfile[];models:{id:string;label:string}[]}){
 const [model,setModel]=useState("bgnbd");const [horizon,setHorizon]=useState(90);const [inactivity,setInactivity]=useState(inactivityOptions[0]);const [frequency,setFrequency]=useState(frequencyOptions[0]);const [cost,setCost]=useState(1);const [margin,setMargin]=useState(30);
 const matching=profiles.filter(x=>x.horizon_days===horizon&&x.inactivity===inactivity&&x.frequency===frequency);const row=matching.find(x=>x.model===model);const breakEven=row?.predicted_spend_per_purchase?cost/(margin/100*row.predicted_spend_per_purchase):null;
 function reset(){setModel("bgnbd");setHorizon(90);setInactivity(inactivityOptions[0]);setFrequency(frequencyOptions[0]);setCost(1);setMargin(30);}
 return <div id="interactive-results" tabIndex={-1} className="program-explorer" data-testid="customer-return-evidence"><p className="explorer-context">Interactive results · the executive summary above remains the fixed headline comparison.</p><div className="explorer-heading"><div><p className="eyebrow">HISTORICAL CUSTOMER EXPLORER</p><h3>Separate a likely purchase from an incremental purchase.</h3></div><button type="button" className="catalog-reset" onClick={reset}>Reset customer comparison</button></div><p>Select saved forecasts for a historical cohort. Cost and margin change only the hypothetical break-even calculation; they do not change evaluated accuracy or establish campaign lift.</p><div className="program-controls"><ModelSelect label="Customer forecast model" models={models} value={model} onChange={setModel} /><label>Purchase horizon<select value={horizon} onChange={e=>setHorizon(Number(e.target.value))}>{[30,60,90].map(h=><option key={h} value={h}>{h} days</option>)}</select></label><label>Time since last purchase<select value={inactivity} onChange={e=>setInactivity(e.target.value)}>{inactivityOptions.map(x=><option key={x}>{x}</option>)}</select></label><label>Prior purchase-day history<select value={frequency} onChange={e=>setFrequency(e.target.value)}>{frequencyOptions.map(x=><option key={x}>{x}</option>)}</select></label></div>
 <div aria-live="polite">{!row?<p className="executive-caution">This cohort has fewer than 50 evaluated customer-window observations. Its results are withheld; broaden the purchase-history or inactivity filter.</p>:<><p>{row.observations.toLocaleString("en-US")} customer-window observations · {row.unique_customers.toLocaleString("en-US")} distinct customers · {horizon}-day horizon. Customers can recur across the three final forecast dates.</p><div className="executive-stats"><div><strong>{pct(row.predicted_purchase_probability)}</strong><span>predicted chance of any purchase</span></div><div><strong>{pct(row.observed_purchase_probability)}</strong><span>observed windows with a purchase</span></div><div><strong>{row.predicted_count.toFixed(2)} / {row.observed_count.toFixed(2)}</strong><span>predicted / observed purchase days</span></div></div><p>Gross positive spend per customer-window: <strong>{gbp(row.predicted_spend_gbp)} predicted</strong> versus <strong>{gbp(row.observed_spend_gbp)} observed</strong>. A purchase day combines all positive purchases on one date; gross value excludes returns and is not profit.</p>{row.latent_alive_probability!==null&&<p>Latent model activity: {pct(row.latent_alive_probability)}. This is different from purchasing within {horizon} days and is not observed retention. BG/NBD fixes activity at 100% for customers with no repeat purchase.</p>}
 <div className="executive-caution"><p className="eyebrow">ASSUMED ECONOMICS / SCENARIO ONLY</p><h4>What would contact need to cause?</h4><div className="program-controls"><label>Contact cost · assumed pounds<input type="range" min="0" max="5" step="0.25" value={cost} aria-valuetext={`${gbp(cost)} assumed cost per contact`} onChange={e=>setCost(Number(e.target.value))}/><output>{gbp(cost)} per contact · assumed</output></label><label>Contribution margin · assumed<input type="range" min="10" max="50" step="5" value={margin} aria-valuetext={`${margin} percent assumed contribution margin`} onChange={e=>setMargin(Number(e.target.value))}/><output>{margin}% of gross purchase value · assumed</output></label></div>{breakEven===null?<p>No positive expected purchase value is available for this cohort, so a break-even threshold cannot be calculated.</p>:<><p>{gbp(cost)} ÷ ({margin}% × {gbp(row.predicted_spend_per_purchase!)}) = <strong>{(100*breakEven).toFixed(2)} percentage points of incremental purchase probability</strong>.</p><p>Assumes one additional purchase day at the model’s predicted value. {breakEven>1?"The required increment exceeds 100%, so break-even is infeasible under these assumptions. ":""}No win-back intervention was observed. This threshold is not expected lift or campaign ROI; ordinary predicted purchasing is not incremental response.</p></>}</div>
 {row.count_coverage_90!==null?<p>Nominal 90% predictive bands covered {pct(row.count_coverage_90)} of count outcomes (average width {row.count_interval_width!.toFixed(2)} purchase days) and {pct(row.spend_coverage_90!)} of spend outcomes (average width {gbp(row.spend_interval_width!)}). These are empirical coverage rates for individual customer-windows, not confidence intervals for this cohort average.</p>:<p>This rule has no evaluated predictive bands; the comparison reports its mean and probability forecasts only.</p>}
 {row.predicted_count_distribution?<><figure className="capacity-chart inventory-chart" tabIndex={0}><svg viewBox="0 0 720 285" role="img" aria-labelledby="customer-distribution-title"><title id="customer-distribution-title">Predicted and observed purchase-day distribution for the selected customer cohort</title>{row.observed_count_distribution.map((actual,i)=>{const x=60+i*105;return <g key={i}><rect x={x} y={230-200*row.predicted_count_distribution![i]} width="30" height={200*row.predicted_count_distribution![i]} fill="#0a192f"/><rect x={x+33} y={230-200*actual} width="30" height={200*actual} fill="#925322"/><text x={x+32} y="252" textAnchor="middle">{i===5?"5+":i}</text></g>;})}{[0,.5,1].map(p=><g key={p}><line x1="45" x2="690" y1={230-200*p} y2={230-200*p} stroke="#cbd5e1"/><text x="38" y={234-200*p} textAnchor="end">{100*p}%</text></g>)}<text x="365" y="278" textAnchor="middle">Future purchase days</text></svg><figcaption>Navy: model distribution from 2,000 predictive draws per observation. Copper: actual frequency. The last bin contains five or more purchase days; the distribution conditions on fitted population parameters.</figcaption></figure><div className="program-table-wrap" tabIndex={0} role="region" aria-label="Customer purchase distribution"><table><caption>{horizon}-day purchase distribution · selected cohort</caption><thead><tr><th scope="col">Purchase days</th><th scope="col">Predicted</th><th scope="col">Observed</th></tr></thead><tbody>{row.observed_count_distribution.map((x,i)=><tr key={i}><th scope="row">{i===5?"5+":i}</th><td>{pct(row.predicted_count_distribution![i])}</td><td>{pct(x)}</td></tr>)}</tbody></table></div></>:<p>A full predictive count distribution was evaluated only for BG/NBD. Select that model to inspect the distribution; a mean forecast alone does not supply one.</p>}</>}</div>
 {row&&<div className="program-table-wrap" tabIndex={0} role="region" aria-label="Customer cohort model comparison"><table><caption>{horizon}-day saved forecasts · {inactivity} · {frequency}</caption><thead><tr><th scope="col">Model</th><th scope="col">Purchase probability</th><th scope="col">Expected purchase days</th><th scope="col">Gross spend</th></tr></thead><tbody>{matching.map(x=><tr key={x.model}><th scope="row">{models.find(m=>m.id===x.model)!.label}</th><td>{pct(x.predicted_purchase_probability)}</td><td>{x.predicted_count.toFixed(3)}</td><td>{gbp(x.predicted_spend_gbp)}</td></tr>)}<tr><th scope="row">Observed</th><td>{pct(row.observed_purchase_probability)}</td><td>{row.observed_count.toFixed(3)}</td><td>{gbp(row.observed_spend_gbp)}</td></tr></tbody></table></div>}<p className="caption">Historical cohorts are descriptive, with repeated customers and uneven seasonal performance. The primary comparison’s customer-bootstrap intervals appear above. These aggregate filters do not run training, produce individual contact lists or demonstrate causal effects.</p></div>;
}
