import results from "@/lib/marketing-results.json";
import { IncrementalityExplorer } from "@/components/incrementality-explorer";
const dollars = (n: number) => `$${n.toFixed(2)}`;
const percent = (n: number) => `${(n * 100).toFixed(1)}%`;
const scenarioNames: Record<string, string> = { base: "Base process", null: "Zero effect", weak_covariate: "Historical relationship weakens", skewed_noise: "Skewed outcomes" };
export function FlagshipEvidence() {
  return <>
    <p className="evidence-disclosure">SYNTHETIC EVALUATION · NO CLIENT DATA OR ACTUAL BUSINESS IMPACT</p>
    <div className="evidence-stats"><div><strong>6,000</strong><span>Randomized customers</span></div><div><strong>$8.00</strong><span>Known assignment effect</span></div><div><strong>{percent(results.interval_width_reduction)}</strong><span>Narrower adjusted interval</span></div></div>
    <p>Exactly 1,500 campaign and 1,500 holdout customers per segment. The estimand is incremental 28-day net contribution before campaign cost, averaged over all assigned customers.</p>
    <div className="table-scroll" tabIndex={0} role="region" aria-label="Primary synthetic estimates"><table className="evidence-table"><caption>Primary experiment · 95% large-sample intervals</caption><thead><tr><th scope="col">Estimator</th><th scope="col">Effect / customer</th><th scope="col">95% interval</th></tr></thead><tbody>{(["unadjusted", "adjusted"] as const).map(name=><tr key={name}><th scope="row">{name === "adjusted" ? "Pre-period adjusted" : "Unadjusted baseline"}</th><td>{dollars(results.estimates[name].estimate)}</td><td>{dollars(results.estimates[name].ci_low)}–{dollars(results.estimates[name].ci_high)}</td></tr>)}</tbody></table></div>
    <IncrementalityExplorer />
    <h3>What held up—and what did not.</h3>
    <ul className="evaluation-list"><li>Across 400 base-scenario experiments with 2,000 customers each, adjusted intervals covered the true effect in {percent(results.monte_carlo.base.adjusted.coverage)} of runs. The Monte Carlo standard error of that coverage is {(100*results.monte_carlo.base.adjusted.coverage_mcse).toFixed(2)} percentage points.</li><li>Under the zero-effect scenario, the adjusted procedure rejected zero in {percent(results.monte_carlo.null.adjusted.rejection_rate)} of runs. This is a simulation check on false positives, not a guarantee for every study.</li><li>When the historical relationship weakened, adjustment worsened RMSE: {dollars(results.monte_carlo.weak_covariate.adjusted.rmse)} versus {dollars(results.monte_carlo.weak_covariate.unadjusted.rmse)} for the baseline. A more elaborate method does not always help.</li><li>The pre-period placebo estimate was {dollars(results.placebo_pre_period.estimate)}, with interval {dollars(results.placebo_pre_period.ci_low)} to {dollars(results.placebo_pre_period.ci_high)}. It includes zero; passing this diagnostic does not prove every design assumption.</li></ul>
    <details><summary>Supplementary simulation diagnostics</summary><p>400 repetitions per scenario, 2,000 customers each; identical seeds across scenarios allow controlled comparisons. Historical slopes stay fixed. Coverage uncertainty is about 1.0–1.2 percentage points (one Monte Carlo standard error).</p><div className="table-scroll" tabIndex={0} role="region" aria-label="Simulation diagnostics"><table className="evidence-table"><caption>Estimator behavior under four declared data processes</caption><thead><tr><th scope="col">Scenario</th><th scope="col">Method</th><th scope="col">Bias</th><th scope="col">RMSE</th><th scope="col">Coverage</th><th scope="col">Reject zero</th></tr></thead><tbody>{Object.entries(results.monte_carlo).flatMap(([scenario, methods])=>Object.entries(methods).map(([name, value])=><tr key={`${scenario}-${name}`}><th scope="row">{scenarioNames[scenario]}</th><td>{name}</td><td>{dollars(value.bias)}</td><td>{dollars(value.rmse)}</td><td>{percent(value.coverage)}</td><td>{percent(value.rejection_rate)}</td></tr>))}</tbody></table></div><p className="caption">Normal intervals can misbehave with smaller samples, heavier tails, dependence or missing data. The full JSON also includes empirical standard deviation and mean estimated standard error. These four scenarios are selected diagnostics, not an exhaustive validation.</p></details>
  </>;
}
