"use client";
import { CapacitySlider } from "@/components/capacity-slider";
import { ModelSelect } from "@/components/model-select";
import { useState } from "react";
import type { InspectionCapacity, SensorStability } from "@/lib/inspection-results";
type Metric={model:string;name:string;estimate:number;lower:number;upper:number};
type Calibration={model:string;bin:number;entities:number;failures:number;mean_probability:number;observed_failure_rate:number};
export function InspectionEvidence({rows,sensors,models,metrics,calibration}:{rows:InspectionCapacity[];sensors:SensorStability[];models:{id:string;label:string}[];metrics:Metric[];calibration:Calibration[]}){
 const [model,setModel]=useState("boosting");const [budget,setBudget]=useState(4);const [threshold,setThreshold]=useState(.8);const [finalOnly,setFinalOnly]=useState(false);
 const capacities=rows.filter(x=>x.model===model);const row=capacities[budget];const comparison=rows.filter(x=>x.capacity===row.capacity);const ap=metrics.find(x=>x.model===model&&x.name==="average_precision")!;const selected=sensors.filter(x=>x.selection_frequency>=threshold&&(!finalOnly||x.selected_in_final));
 function reset(){setModel("boosting");setBudget(4);setThreshold(.8);setFinalOnly(false);}
 return <div id="interactive-results" tabIndex={-1} className="program-explorer" data-testid="inspection-evidence"><p className="explorer-context">Interactive results · the executive summary above remains the fixed headline comparison.</p><div className="explorer-heading"><div><p className="eyebrow">HISTORICAL INSPECTION EXPLORER</p><h3>How many failures remain outside the review queue?</h3></div><button type="button" className="catalog-reset" onClick={reset}>Reset inspection comparison</button></div><p>Controls display saved October results. The inspection share is an assumed batch budget; moving it does not refit a model or prevent a failure.</p><div className="program-controls"><ModelSelect label="Screening model" models={models.filter(x=>x.id!=="prevalence")} value={model} onChange={setModel} /><label>Inspection share of final batch · assumed budget<CapacitySlider points={capacities.map(value => value.capacity * 100)} index={budget} onChange={setBudget} valueText={`${Math.round(row.capacity*100)} percent; ${row.inspections} of 359 units`} /><output>{Math.round(row.capacity*100)}% · {row.inspections} of 359 units</output></label></div><div aria-live="polite"><div className="executive-stats"><div><strong>{row.detected_failures} / 22</strong><span>observed failures identified</span></div><div><strong>{row.missed_failures}</strong><span>observed failures outside the queue</span></div><div><strong>{row.unnecessary_inspections}</strong><span>inspected units that passed</span></div></div><p>{(100*row.recall).toFixed(1)}% of failures captured. Queue precision: {row.precision===null?"undefined with no inspections":`${(row.precision*100).toFixed(1)}%`}. These are exact counts in one historical cohort; future detection is uncertain.</p><p className="executive-caution">This model’s average precision across thresholds is {ap.estimate.toFixed(4)} (95% day-cluster interval {ap.lower.toFixed(4)}–{ap.upper.toFixed(4)}). That metric differs from recall at the chosen budget. Only 17 final days and 22 failures support the evaluation.</p></div>
 <figure className="capacity-chart inventory-chart" tabIndex={0}><svg viewBox="0 0 660 330" role="img" aria-labelledby="inspection-curve-title"><title id="inspection-curve-title">Observed failures identified as batch inspection capacity increases</title>{[0,5,10,15,20].map(v=><g key={v}><line x1="65" x2="610" y1={275-v*10} y2={275-v*10} className="chart-grid"/><text x="54" y={280-v*10} textAnchor="end">{v}</text></g>)}{[0,.25,.5,.75,1].map(v=><text key={v} x={65+545*v} y="304" textAnchor="middle">{100*v}%</text>)}<polyline fill="none" stroke="#925322" strokeWidth="3" points={capacities.map(x=>`${65+545*x.capacity},${275-10*x.detected_failures}`).join(" ")}/><circle cx={65+545*row.capacity} cy={275-10*row.detected_failures} r="7" fill="#0a192f"/><text x="65" y="25">Failures identified · selected model</text></svg><figcaption>Horizontal: assumed share of the complete final batch inspected. Vertical: observed failures captured. At 100%, all 22 labels are recovered by construction. The curve is a historical ranking replay, not measured defect reduction.</figcaption></figure>
 <div className="program-table-wrap" tabIndex={0} role="region" aria-label="Inspection model comparison"><table><caption>{Math.round(row.capacity*100)}% inspection budget · same 359 final entities</caption><thead><tr><th scope="col">Model</th><th scope="col">Inspections</th><th scope="col">Detected failures</th><th scope="col">Missed failures</th><th scope="col">Inspected passes</th></tr></thead><tbody>{comparison.map(x=><tr key={x.model}><th scope="row">{models.find(m=>m.id===x.model)!.label}</th><td>{x.inspections}</td><td>{x.detected_failures}</td><td>{x.missed_failures}</td><td>{x.unnecessary_inspections}</td></tr>)}</tbody></table></div>
 <details><summary>Probability calibration for the selected model</summary><div className="program-table-wrap" tabIndex={0} role="region" aria-label="Screening probability calibration"><table><caption>Five equal-count score groups · descriptive, not recalibrated</caption><thead><tr><th scope="col">Group</th><th scope="col">Units</th><th scope="col">Failures</th><th scope="col">Mean predicted risk</th><th scope="col">Observed failure rate</th></tr></thead><tbody>{calibration.filter(x=>x.model===model).map(x=><tr key={x.bin}><th scope="row">{x.bin}</th><td>{x.entities}</td><td>{x.failures}</td><td>{(100*x.mean_probability).toFixed(1)}%</td><td>{(100*x.observed_failure_rate).toFixed(1)}%</td></tr>)}</tbody></table></div></details>
 <h4>Which anonymous signals are repeatedly selected?</h4><p>These results always describe the sparse logistic model’s 30 training-day bootstrap refits. They are separate from the selected screening model above. Frequency is not physical importance or proof of a fault.</p><div className="program-controls"><label>Minimum sensor-selection frequency<select value={threshold} onChange={e=>setThreshold(Number(e.target.value))}>{[.1,.25,.5,.8,1].map(v=><option key={v} value={v}>{100*v}% of refits</option>)}</select></label><label className="checkbox-control"><input type="checkbox" checked={finalOnly} onChange={e=>setFinalOnly(e.target.checked)}/>Only sensors selected in the final sparse fit</label></div><p aria-live="polite">{selected.length} sensors meet this display filter. Showing the first {Math.min(selected.length,12)} by selection frequency; the aggregate download contains all recorded sensors.</p><div className="program-table-wrap" tabIndex={0} role="region" aria-label="Sensor selection stability"><table><caption>Anonymous source columns · 30 refits</caption><thead><tr><th scope="col">Sensor</th><th scope="col">Selected</th><th scope="col">Available after filtering</th><th scope="col">In final fit</th></tr></thead><tbody>{selected.slice(0,12).map(x=><tr key={x.sensor}><th scope="row">{x.sensor}</th><td>{(100*x.selection_frequency).toFixed(1)}%</td><td>{(100*x.availability_frequency).toFixed(1)}%</td><td>{x.selected_in_final?"Yes":"No"}</td></tr>)}</tbody></table></div><p className="caption">Model uncertainty conditions on the fitted models and this historical period. Sensors lack physical names and acquisition timestamps. A display threshold changes the table only; it does not create a new sensor model or alter held-out accuracy.</p></div>;
}
