"use client";
import { ModelSelect } from "@/components/model-select";
import { formatCurrency } from "@/lib/format";
import { useState } from "react";
import type { InsuranceScenario } from "@/lib/insurance-results";
const euro = (value: number, digits = 2) => formatCurrency(value, digits, "EUR");
const count=(x:number)=>x.toLocaleString("en-US");
export function InsuranceEvidence({scenarios,models}:{scenarios:{uncapped:InsuranceScenario;capped:InsuranceScenario};models:{id:string;label:string}[]}){
 const [basis,setBasis]=useState<"uncapped"|"capped">("uncapped");const [model,setModel]=useState("boosting");const [group,setGroup]=useState("portfolio::All policies");const [loading,setLoading]=useState(20);
 const current=scenarios[basis];const row=current.segments.find(x=>x.model===model&&`${x.grouping}::${x.group}`===group)!;const comparisons=current.segments.filter(x=>`${x.grouping}::${x.group}`===group);const options=current.segments.filter(x=>x.model===model);const maximum=Math.max(2,...comparisons.map(x=>x.ratio_upper))*1.05;
 function reset(){setBasis("uncapped");setModel("boosting");setGroup("portfolio::All policies");setLoading(20);}
 return <div id="interactive-results" tabIndex={-1} className="program-explorer" data-testid="insurance-evidence"><p className="explorer-context">Interactive results · the executive summary above remains the fixed headline comparison.</p><div className="explorer-heading"><div><p className="eyebrow">HISTORICAL LOSS EXPLORER</p><h3>Compare the expected loss with the loss actually recorded.</h3></div><button type="button" className="catalog-reset" onClick={reset}>Reset insurance comparison</button></div><p>Model, loss basis and cohort controls select saved final results. Expense loading is a hypothetical calculation; it does not change the measured model comparison.</p><div className="program-controls"><ModelSelect label="Pricing model" models={models} value={model} onChange={setModel} /><label>Loss basis<select value={basis} onChange={e=>setBasis(e.target.value as "uncapped"|"capped")}><option value="uncapped">Full recorded claims</option><option value="capped">€50,000 cap sensitivity</option></select></label><label>Final policy cohort<select value={group} onChange={e=>setGroup(e.target.value)}>{options.map(x=><option key={`${x.grouping}::${x.group}`} value={`${x.grouping}::${x.group}`}>{x.grouping==="portfolio"?x.group:`${x.grouping==="driver_age"?"Driver age":x.grouping}: ${x.group}`}</option>)}</select></label></div>
 <div aria-live="polite"><p>{count(row.policies)} final policies · {count(row.claims)} claims · {row.exposure_years.toLocaleString("en-US",{maximumFractionDigits:1})} policy-years · {basis==="uncapped"?"full recorded loss":"€50,000 per-claim capped loss"}</p><div className="executive-stats"><div><strong>{euro(row.predicted_pure_premium)}</strong><span>estimated loss per policy-year</span></div><div><strong>{euro(row.observed_pure_premium)}</strong><span>observed loss per policy-year</span></div><div><strong>{row.predicted_observed_loss_ratio!.toFixed(2)}×</strong><span>predicted / observed total loss</span></div></div><p>Calibration ratio 95% interval: {row.ratio_lower.toFixed(2)}–{row.ratio_upper.toFixed(2)}. A ratio of 1 matches recorded total loss; below 1 underpredicts it. These intervals describe the observed sample, conditional on the fitted model.</p><div className="executive-takeaway"><h4>Separate claim frequency from claim size.</h4><p>Observed: {(100*row.observed_frequency).toFixed(2)} claims per 100 policy-years × {row.observed_severity===null?"undefined severity":`${euro(row.observed_severity)} per claim`}.</p><p>{row.predicted_frequency===null?"Direct Tweedie predicts total expected loss only; it has no fitted frequency–severity decomposition.":`Estimated: ${(100*row.predicted_frequency).toFixed(2)} claims per 100 policy-years × ${euro(row.predicted_severity!)} per claim. Severity is weighted by predicted claim frequency across this cohort.`}</p></div><div className="executive-caution"><p className="eyebrow">ASSUMED ECONOMICS / SCENARIO ONLY</p><h4>Illustrative expense calculation</h4><div className="program-controls"><label>Expense loading · assumed share of gross premium<input type="range" min="0" max="50" step="5" value={loading} aria-valuetext={`${loading} percent assumed expense loading`} onChange={e=>setLoading(Number(e.target.value))}/><output>{loading}% · assumed</output></label></div><p>{euro(row.predicted_pure_premium)} ÷ (1 − {(loading/100).toFixed(2)}) = <strong>{euro(row.predicted_pure_premium/(1-loading/100))} per policy-year</strong>.</p><p>The {loading}% expense share is assumed. This is not an insurance quote or proposed rate; profit, taxes, capital, reinsurance and regulatory constraints are excluded. A loading cannot repair a miscalibrated loss estimate.</p></div></div>
 <figure className="capacity-chart inventory-chart" tabIndex={0}><svg viewBox="0 0 720 250" role="img" aria-labelledby="insurance-calibration-title"><title id="insurance-calibration-title">Predicted to observed loss ratios and 95 percent policy bootstrap intervals for the selected cohort</title><line x1={220+460/maximum} x2={220+460/maximum} y1="20" y2="196" stroke="#64748b" strokeDasharray="5 4"/>{comparisons.map((x,i)=>{const y=45+i*44;return <g key={x.model}><text x="207" y={y+4} textAnchor="end">{x.model==="constant"?"Portfolio mean":x.model==="glm"?"Poisson–Gamma":x.model==="tweedie"?"Direct Tweedie":"Boosted model"}</text><line x1={220+460*x.ratio_lower/maximum} x2={220+460*x.ratio_upper/maximum} y1={y} y2={y} stroke="#925322" strokeWidth="3"/><circle cx={220+460*x.predicted_observed_loss_ratio!/maximum} cy={y} r="5" fill="#0a192f"/></g>;})}{[0,1,maximum].map((x,i)=><text key={i} x={220+460*x/maximum} y="223" textAnchor="middle">{x.toFixed(1)}×</text>)}</svg><figcaption>{row.group}: dots show predicted/observed total loss; lines show paired-policy bootstrap intervals. The dashed line at 1 is exact portfolio calibration. Wide intervals are part of the evidence.</figcaption></figure>
 <div className="program-table-wrap" tabIndex={0} role="region" aria-label="Insurance cohort model comparison"><table><caption>{row.group} · {basis==="uncapped"?"full recorded claims":"€50,000 per-claim sensitivity"}</caption><thead><tr><th scope="col">Model</th><th scope="col">Estimated €/policy-year</th><th scope="col">Predicted / observed</th><th scope="col">95% interval</th></tr></thead><tbody>{comparisons.map(x=><tr key={x.model}><th scope="row">{models.find(m=>m.id===x.model)!.label}</th><td>{euro(x.predicted_pure_premium)}</td><td>{x.predicted_observed_loss_ratio!.toFixed(3)}</td><td>{x.ratio_lower.toFixed(3)}–{x.ratio_upper.toFixed(3)}</td></tr>)}</tbody></table></div>
 <details><summary>Portfolio risk-group calibration for the selected model</summary><p>Ten equal-count score groups use the entire final portfolio, independent of the cohort selector above. They describe calibration; they are not ten independent experiments.</p><div className="program-table-wrap" tabIndex={0} role="region" aria-label="Insurance risk group calibration"><table><caption>{models.find(x=>x.id===model)!.label} · {basis} loss · whole final portfolio</caption><thead><tr><th scope="col">Risk group</th><th scope="col">Policies</th><th scope="col">Claims</th><th scope="col">Estimated €/year</th><th scope="col">Observed €/year</th><th scope="col">Ratio</th></tr></thead><tbody>{current.calibration.filter(x=>x.model===model).map(x=><tr key={x.bin}><th scope="row">{x.bin}</th><td>{count(x.policies)}</td><td>{count(x.claims)}</td><td>{euro(x.predicted_pure_premium)}</td><td>{euro(x.observed_pure_premium)}</td><td>{x.predicted_observed_loss_ratio!.toFixed(2)}</td></tr>)}</tbody></table></div></details><p className="caption">Cohorts require at least 500 final policies. Empirical intervals omit unseen catastrophic losses and unobserved dependence. The capped analysis changes the target; it does not establish the full-loss model’s performance.</p></div>;
}
