"use client";
import { ModelSelect } from "@/components/model-select";
import { formatCurrency, formatPercent } from "@/lib/format";
import { useState } from "react";
import type { InventoryScenario, InventoryForecast, InventoryOrigin } from "@/lib/inventory-results";
const money = (value: number, digits = 2) => formatCurrency(value, digits, "USD");
const count=(x:number)=>x.toLocaleString("en-US",{maximumFractionDigits:0});
const percent = formatPercent;
export function InventoryEvidence({scenarios,forecasts,origins,models,demand}:{scenarios:InventoryScenario[];forecasts:InventoryForecast[];origins:InventoryOrigin[];models:{id:string;label:string}[];demand:number}){
 const [model,setModel]=useState("quantile_boosting");const [group,setGroup]=useState("selected assortment");const [lead,setLead]=useState(3);const [holding,setHolding]=useState(.01);const [penalty,setPenalty]=useState(1);const [capacity,setCapacity]=useState(1);
 const groups=[...new Set(forecasts.map(x=>x.group))];const names=[...models,{id:"conventional_mean",label:"Conventional prior-cycle target"}];
 const sid=`L${lead}-H${holding}-P${penalty}-K${capacity}`;const rows=scenarios.filter(x=>x.scenario_id===sid);const selected=rows.find(x=>x.model===model)!;
 const bands=forecasts.filter(x=>x.model===model&&x.group===group);const maxForecast=Math.max(1,...bands.flatMap(x=>[x.upper_units,x.observed_sales_units,x.point_units]));const fy=(v:number)=>260-205*v/maxForecast;
 const frontier=scenarios.filter(x=>x.model===model&&x.lead_days===lead&&x.holding_per_unit_day===holding&&x.lost_sale_penalty===penalty).sort((a,b)=>a.storage_multiplier-b.storage_multiplier);
 const maxCost=Math.max(...frontier.map(x=>x.assumed_cost),1);const selectedOrigins=origins.filter(x=>x.scenario_id===sid&&x.model===model);const orders=selectedOrigins.reduce((sum,x)=>sum+x.order_units,0);
 function reset(){setModel("quantile_boosting");setGroup("selected assortment");setLead(3);setHolding(.01);setPenalty(1);setCapacity(1);}
 return <div id="interactive-results" tabIndex={-1} className="program-explorer" data-testid="inventory-evidence"><p className="explorer-context">Interactive results · the executive summary above remains the fixed headline comparison.</p><div className="explorer-heading"><div><p className="eyebrow">FORECAST & INVENTORY EXPLORER</p><h3>Choose the service–cost tradeoff explicitly.</h3></div><button type="button" className="catalog-reset" onClick={reset}>Reset inventory comparison</button></div><p>Forecasts are saved historical evaluations. Economic controls select one of 36 precomputed simulations; they do not change measured forecast accuracy or retrain the models.</p><div className="program-controls"><ModelSelect label="Forecast model" models={models} value={model} onChange={setModel} /><label>Forecast aggregation<select value={group} onChange={e=>setGroup(e.target.value)}>{groups.map(x=><option key={x} value={x}>{x}</option>)}</select></label></div>
 <figure className="capacity-chart inventory-chart" tabIndex={0}><svg viewBox="0 0 660 320" role="img" aria-labelledby="inventory-band-title inventory-band-desc"><title id="inventory-band-title">Observed sales and saved 80% forecast bands</title><desc id="inventory-band-desc">Four final 28-day windows for the selected model and group. Exact quantities and coverage are in the following table.</desc>{[0,.25,.5,.75,1].map(v=><g key={v}><line x1="80" x2="625" y1={fy(maxForecast*v)} y2={fy(maxForecast*v)} className="chart-grid"/><text x="70" y={fy(maxForecast*v)+4} textAnchor="end">{count(maxForecast*v)}</text></g>)}{bands.map((b,i)=><g key={b.origin}><line x1={140+i*140} x2={140+i*140} y1={fy(b.lower_units)} y2={fy(b.upper_units)} stroke="#64748b" strokeWidth="12" opacity=".35"/><circle cx={140+i*140} cy={fy(b.point_units)} r="5" fill="#925322"/><path d={`M${134+i*140} ${fy(b.observed_sales_units)-6} l12 12 m-12 0 l12 -12`} stroke="#0a192f" strokeWidth="2"/><text x={140+i*140} y="285" textAnchor="middle">Window {i+1}</text></g>)}<text x="80" y="24">Recorded sales units over 28 days</text></svg><figcaption>Slate bands: empirical 80% forecast ranges. Copper dots: summed point forecasts. Navy crosses: observed sales. Dates below are forecast origins. On narrow screens, scroll the chart horizontally.</figcaption></figure>
 <div className="program-table-wrap" tabIndex={0} role="region" aria-label="Saved inventory forecast values"><table><caption>{group} · historical forecasts</caption><thead><tr><th scope="col">Origin</th><th scope="col">Observed units</th><th scope="col">Forecast units</th><th scope="col">80% range</th><th scope="col">Covered?</th></tr></thead><tbody>{bands.map(b=><tr key={b.origin}><th scope="row">{b.forecast_date}</th><td>{count(b.observed_sales_units)}</td><td>{count(b.point_units)}</td><td>{count(b.lower_units)}–{count(b.upper_units)}</td><td>{b.covered?"Yes":"No"}</td></tr>)}</tbody></table></div><p className="caption">Bands use 17 overlapping calibration histories and are not guaranteed to cover future outcomes. Summing bottom-level scenarios preserves accounting; aggregate quantiles are calculated after summing. The summed point forecast is a separate statistic and can fall outside the aggregate scenario band.</p>
 <div className="scenario-panel"><p className="eyebrow">ASSUMED ECONOMICS / SCENARIO ONLY</p><h3>One order, limited space and an explicit arrival date.</h3><p>Observed daily sales are replayed as hypothetical demand. Actual inventory availability and costs are unknown. All results below combine the same 210 series and four final windows; the forecast aggregation selector changes only the chart above.</p><div className="program-controls"><label>Assumed lead time<select value={lead} onChange={e=>setLead(Number(e.target.value))}>{[0,3,7].map(x=><option key={x} value={x}>{x} days</option>)}</select></label><label>Assumed holding cost<select value={holding} onChange={e=>setHolding(Number(e.target.value))}>{[.01,.05].map(x=><option key={x} value={x}>{money(x)} / unit / day</option>)}</select></label><label>Assumed penalty for a lost sale<select value={penalty} onChange={e=>setPenalty(Number(e.target.value))}>{[1,5].map(x=><option key={x} value={x}>{money(x)} / unmet unit</option>)}</select></label><label>Assumed storage capacity<select value={capacity} onChange={e=>setCapacity(Number(e.target.value))}>{[.5,1,2].map(x=><option key={x} value={x}>{x}× previous 28-day sales</option>)}</select></label></div>
 <div className="executive-stats" aria-live="polite"><div><strong>{money(selected.assumed_cost)}</strong><span>total assumed cost</span></div><div><strong>{percent(1-selected.lost_units/demand)}</strong><span>scenario unit fill rate</span></div><div><strong>{count(orders)}</strong><span>ordered units across four cycles</span></div></div><p>Cost difference versus the conventional target: <strong>{money(selected.cost_difference_vs_conventional)}</strong>; paired 95% item-cluster interval <strong>{money(selected.cost_difference_interval.lower)} to {money(selected.cost_difference_interval.upper)}</strong>. Negative values favor the selected policy under these assumptions.</p>
 <figure className="capacity-chart inventory-chart" tabIndex={0}><svg viewBox="0 0 660 320" role="img" aria-labelledby="inventory-cost-title inventory-cost-desc"><title id="inventory-cost-title">Storage capacity, simulated service and assumed cost</title><desc id="inventory-cost-desc">Three points show one-half, one and two times prior-cycle sales as storage capacity. Table values follow.</desc>{[0,.25,.5,.75,1].map(v=><g key={v}><line x1="85" x2="615" y1={260-v*205} y2={260-v*205} className="chart-grid"/><text x="75" y={264-v*205} textAnchor="end">${count(maxCost*v)}</text><text x={85+v*530} y="285" textAnchor="middle">{Math.round(v*100)}%</text></g>)}<polyline className="chart-policy" points={frontier.map(x=>`${85+(1-x.lost_units/demand)*530},${260-x.assumed_cost/maxCost*205}`).join(" ")}/>{frontier.map(x=><g key={x.storage_multiplier}><circle className="chart-selected" cx={85+(1-x.lost_units/demand)*530} cy={260-x.assumed_cost/maxCost*205} r={x.storage_multiplier===capacity?7:4}/><text x={85+(1-x.lost_units/demand)*530-8} y={250-x.assumed_cost/maxCost*205} textAnchor="end">{x.storage_multiplier}×</text></g>)}<text x="85" y="24">Assumed total cost (USD)</text><text x="350" y="315" textAnchor="middle">Scenario unit fill rate (%)</text></svg><figcaption>Saved sensitivity points for the selected forecast and costs. Larger point: chosen storage. This finite grid is not a globally optimized frontier.</figcaption></figure>
 <div className="program-table-wrap" tabIndex={0} role="region" aria-label="Storage capacity sensitivity"><table><caption>Selected policy · storage sensitivity</caption><thead><tr><th scope="col">Storage multiplier</th><th scope="col">Assumed cost</th><th scope="col">Fill rate</th></tr></thead><tbody>{frontier.map(x=><tr key={x.storage_multiplier}><th scope="row">{x.storage_multiplier}×</th><td>{money(x.assumed_cost)}</td><td>{percent(1-x.lost_units/demand)}</td></tr>)}</tbody></table></div>
 <div className="program-table-wrap" tabIndex={0} role="region" aria-label="Inventory policy comparison"><table><caption>All policies · identical scenario constraints</caption><thead><tr><th scope="col">Policy</th><th scope="col">Assumed cost</th><th scope="col">Lost units</th><th scope="col">Hindsight regret</th></tr></thead><tbody>{rows.map(x=><tr key={x.model}><th scope="row">{names.find(n=>n.id===x.model)!.label}</th><td>{money(x.assumed_cost)}</td><td>{count(x.lost_units)}</td><td>{money(x.regret)}</td></tr>)}</tbody></table></div>
 <details><summary>Order quantities and scenario accounting</summary><div className="program-table-wrap" tabIndex={0} role="region" aria-label="Orders by replenishment cycle"><table><caption>Selected policy · aggregate order quantities</caption><thead><tr><th scope="col">Source-day origin</th><th scope="col">Order units</th><th scope="col">Fill rate</th><th scope="col">Assumed cost</th></tr></thead><tbody>{selectedOrigins.map(x=><tr key={x.origin}><th scope="row">d_{x.origin}</th><td>{count(x.order_units)}</td><td>{percent(x.unit_fill_rate)}</td><td>{money(x.assumed_cost)}</td></tr>)}</tbody></table></div><p>Initial stock equals prior average daily sales × lead time, rounded up and capped by space. The single order arrives before demand on day {lead+1}. Space for the entire order is reserved at the origin. Lost demand is not backordered.</p><p>Forecast order target: quantile at penalty ÷ (penalty + 28 × daily holding cost), minus initial stock and capped by available space. Cost = end-of-day stock × holding cost + lost units × penalty. No purchase cost or actual profit is measured.</p></details><p className="caption">Hindsight chooses the exact best feasible integer order under the same constraints: {money(selected.hindsight_cost)}. It knows future scenario demand, so its cost is a comparator, not an available operational forecast. Uncertainty resamples fixed item clusters, not future market conditions.</p></div></div>;
}
