"use client";
import { useState } from "react";
import type { PropertyProfile } from "@/lib/property-results";
const money=(x:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(x);
const percentage=(x:number)=>(100*x).toFixed(1)+"%";
export function PropertyEvidence({profiles,models}:{profiles:PropertyProfile[];models:{id:string;label:string}[]}){
 const [town,setTown]=useState("All townships");const [size,setSize]=useState("All sizes");const [model,setModel]=useState("spatial_boosting");const [level,setLevel]=useState(.9);
 const towns=profiles.filter(x=>x.model===model&&x.nominal===level&&x.size_profile==="All sizes");const sizes=profiles.filter(x=>x.model===model&&x.nominal===level&&x.township===town).map(x=>x.size_profile);
 const row=profiles.find(x=>x.township===town&&x.size_profile===size&&x.model===model&&x.nominal===level)!;
 const dots=towns.filter(x=>x.township!=="All townships");const minLat=Math.min(...dots.map(x=>x.latitude))-.03;const maxLat=Math.max(...dots.map(x=>x.latitude))+.03;const minLon=Math.min(...dots.map(x=>x.longitude))-.03;const maxLon=Math.max(...dots.map(x=>x.longitude))+.03;
 const mx=(v:number)=>75+(v-minLon)/(maxLon-minLon)*480;const my=(v:number)=>360-(v-minLat)/(maxLat-minLat)*300;
 const top=Math.max(row.observed_price_q90_USD,row.median_upper_USD)*1.05;const px=(v:number)=>75+v/top*500;
 function changeTown(value:string){setTown(value);setSize("All sizes");}
 function reset(){setTown("All townships");setSize("All sizes");setModel("spatial_boosting");setLevel(.9);}
 return <div className="program-explorer" data-testid="property-evidence"><div className="explorer-heading"><div><p className="eyebrow">HISTORICAL PROPERTY EXPLORER</p><h3>Does the uncertainty hold in this local market?</h3></div><button type="button" className="catalog-reset" onClick={reset}>Reset property comparison</button></div><p>Select a historical township and building-size group. Every number comes from evaluated sales; this is not an address-level appraisal or a current market quote.</p><div className="program-controls"><label>Assessment township<select value={town} onChange={e=>changeTown(e.target.value)}>{towns.map(x=><option key={x.township}>{x.township}</option>)}</select></label><label>Observed property profile<select value={size} onChange={e=>setSize(e.target.value)}>{sizes.map(x=><option key={x}>{x}</option>)}</select></label><label>Valuation model<select value={model} onChange={e=>setModel(e.target.value)}>{models.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label><label>Nominal prediction coverage<select value={level} onChange={e=>setLevel(Number(e.target.value))}>{[.8,.9,.95].map(x=><option key={x} value={x}>{100*x}% interval</option>)}</select></label></div>
 <div aria-live="polite"><div className="executive-stats"><div><strong>{row.median_ape_pct.toFixed(2)}%</strong><span>median absolute percentage error</span></div><div><strong>{percentage(row.coverage)}</strong><span>observed interval coverage</span></div><div><strong>{row.sales.toLocaleString("en-US")}</strong><span>held-out sales in this group</span></div></div><p>{row.parcels.toLocaleString("en-US")} distinct parcels · {row.training_comparable_sales.toLocaleString("en-US")} earlier training sales in the same township/size group. These are cohort comparables, not a manually adjudicated set for an individual home.</p><p className={row.coverage<level-.05?"executive-caution":"caption"}>{row.coverage<level-.05?`Coverage is materially below the nominal ${100*level}% target in this historical group. `:"Empirical coverage is shown without a future guarantee. "}This selection changes the evidence shown, not the fitted model or calibration.</p></div>
 <figure className="capacity-chart inventory-chart" tabIndex={0}><svg viewBox="0 0 660 415" aria-labelledby="property-map-title property-map-description"><title id="property-map-title">Historical assessment-township cohort map</title><desc id="property-map-description">Dots are aggregate sale-cohort centroids, not property locations or township boundaries. Use the township selector or focus a named dot and press Enter. Map colors use all-size cohorts at the selected model and nominal coverage.</desc>{[0,.25,.5,.75,1].map(f=><g key={f}><line x1="75" x2="555" y1={60+300*f} y2={60+300*f} className="chart-grid"/><text x="65" y={64+300*f} textAnchor="end">{(maxLat-f*(maxLat-minLat)).toFixed(2)}°N</text><text x={75+480*f} y="387" textAnchor="middle">{Math.abs(minLon+f*(maxLon-minLon)).toFixed(2)}°W</text></g>)}{dots.map(x=><g key={x.township} role="button" tabIndex={0} aria-label={`${x.township}: ${percentage(x.coverage)} coverage, ${x.sales} sales`} aria-pressed={town===x.township} className="property-map-point" onClick={()=>changeTown(x.township)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();changeTown(x.township);}}}><title>{`${x.township} · ${percentage(x.coverage)} coverage · ${x.sales} sales`}</title><circle cx={mx(x.longitude)} cy={my(x.latitude)} r={5+Math.sqrt(x.sales)/7} fill={x.coverage<level-.05?"#925322":"#64748b"} opacity=".8" stroke={town===x.township?"#0a192f":"white"} strokeWidth={town===x.township?4:1}/>{town===x.township?<text x={mx(x.longitude)+14} y={my(x.latitude)-12}>{x.township}</text>:null}</g>)}<text x="75" y="27">Township cohorts · all building sizes</text><text x="580" y="55">N ↑</text></svg><figcaption>Copper: observed coverage more than 5 percentage points below the selected nominal level. Slate: remaining cohorts. Dot size reflects sale count. This is a centroid map, not a boundary map. Historical townships differ from present-day neighborhoods; selecting a dot resets the size group.</figcaption></figure>
 <h4>Historical prices and the model’s uncertainty</h4><div className="program-table-wrap" tabIndex={0} role="region" aria-label="Selected property cohort distribution"><table><caption>{town} · {size} · {100*level}% nominal bands</caption><tbody><tr><th scope="row">Observed sale-price median</th><td>{money(row.observed_price_median_USD)}</td></tr><tr><th scope="row">Observed 10th–90th percentile range</th><td>{money(row.observed_price_q10_USD)}–{money(row.observed_price_q90_USD)}</td></tr><tr><th scope="row">Median predicted price</th><td>{money(row.prediction_median_USD)}</td></tr><tr><th scope="row">Median individual prediction-band endpoints</th><td>{money(row.median_lower_USD)}–{money(row.median_upper_USD)}</td></tr></tbody></table></div>
 <figure className="capacity-chart inventory-chart" tabIndex={0}><svg viewBox="0 0 660 235" role="img" aria-labelledby="property-distribution-title"><title id="property-distribution-title">Observed cohort price spread and median individual prediction band</title><text x="75" y="27">Historical sale-price distribution (USD)</text><line x1={px(row.observed_price_q10_USD)} x2={px(row.observed_price_q90_USD)} y1="75" y2="75" stroke="#0a192f" strokeWidth="10"/><circle cx={px(row.observed_price_median_USD)} cy="75" r="8" fill="white" stroke="#0a192f" strokeWidth="3"/><text x="75" y="115">Median individual {100*level}% prediction band (USD)</text><line x1={px(row.median_lower_USD)} x2={px(row.median_upper_USD)} y1="150" y2="150" stroke="#925322" strokeWidth="10"/><circle cx={px(row.prediction_median_USD)} cy="150" r="8" fill="white" stroke="#925322" strokeWidth="3"/>{[0,.25,.5,.75,1].map(f=><text key={f} x={px(top*f)} y="205" textAnchor="middle">${Math.round(top*f/1000)}k</text>)}</svg><figcaption>Navy: observed 10th–90th percentile sale range with median. Copper: medians of individual prediction-band endpoints and predictions. The two ranges answer different questions; neither is a confidence interval for this township’s market value.</figcaption></figure><p className="caption">At least 30 final sales are required for each displayed group. Global calibration uses 5,828 earlier parcels. Wider nominal intervals change the saved interval endpoints and measured coverage; they do not improve the model’s point accuracy. No personal sale records or exact property locations are displayed.</p></div>;
}
