import type { ReactNode } from "react";
import Link from "next/link";
import { Header, Footer } from "@/components/portfolio";
import type { ProgramStudy } from "@/lib/program-registry";
import { productionOrigin } from "@/lib/site";
export function StudyFrame({study,headline,finding,coverage,code,date,children}:{study:ProgramStudy;headline:string;finding:string;coverage:string;code:string;date:string;children:ReactNode}){
 const structured={"@context":"https://schema.org","@type":"ScholarlyArticle",headline:study.title,author:{"@type":"Person",name:"Michael P. Gibb, Ph.D."},url:`${productionOrigin}/research/${study.slug}`,datePublished:date,citation:study.dataset.url,isAccessibleForFree:true};
 return <><Header/><main id="main" tabIndex={-1}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structured).replace(/</g,"\\u003c")}}/><section className="project-hero program-hero"><div className="shell"><Link className="back-link" href="/research">← Research catalog</Link><p className="eyebrow">{study.id} / {study.industry.toUpperCase()}</p><h1>{headline}</h1><p className="project-question">{finding}</p><div className="project-hero-foot"><span className="status-light">Evaluated public-data study</span><a className="button-light" href={code}>Research code ↗</a><a className="button-light" href="#decision">Executive summary ↓</a></div><p className="program-coverage">{coverage}</p></div></section><div className="shell case-layout"><aside className="case-nav"><p className="eyebrow">IN THIS STUDY</p><nav aria-label="Case study contents"><a href="#decision">Decision & executive summary</a><a href="#implication">Implication</a><a href="#evidence">Evidence</a><a href="#data">Data</a><a href="#method">Method & limitations</a><a href="#code">Code</a></nav></aside><article className="case-body">{children}</article></div></main><Footer/></>;
}
