"use client";
import { useState } from "react";
import type { WorkflowDiagnostic, WorkflowFrontier, WorkflowTransition } from "@/lib/workflow-results";
const clean=(x:string)=>x.replace(/^A_/,"").replaceAll("_"," ");
const pct=(x:number)=>(100*x).toFixed(1)+"%";
export function WorkflowEvidence({diagnostics,frontier,transitions,models}:{diagnostics:WorkflowDiagnostic[];frontier:WorkflowFrontier[];transitions:WorkflowTransition[];models:{id:string;label:string}[]}){
 const [model,setModel]=useState("hazard_boosting");const [prefix,setPrefix]=useState(20);const [stage,setStage]=useState("all");const [capacity,setCapacity]=useState(.2);const [share,setShare]=useState(0);const [multiplier,setMultiplier]=useState(1);
 const stages=diagnostics.filter(x=>x.model===model&&x.prefix===prefix).map(x=>x.stage);
 const row=diagnostics.find(x=>x.model===model&&x.prefix===prefix&&x.stage===stage)!;
 const late=frontier.find(x=>x.model===model&&x.prefix===prefix&&x.capacity===capacity)!;
 const selected=frontier.filter(x=>x.model===model&&x.prefix===prefix);const baseline=frontier.filter(x=>x.model==="stage_age_km"&&x.prefix===prefix);
 const px=(x:number)=>70+x*540;const py=(x:number)=>260-x*210;
 const line=(rows:WorkflowFrontier[])=>rows.map(x=>`${px(x.capacity)},${py(x.capture)}`).join(" ");
 const band=[...selected.map(x=>`${px(x.capacity)},${py(x.capture_interval.upper)}`),...selected.toReversed().map(x=>`${px(x.capacity)},${py(x.capture_interval.lower)}`)].join(" ");
 const factor=(1-share)+share/multiplier;
 function reset(){setModel("hazard_boosting");setPrefix(20);setStage("all");setCapacity(.2);setShare(0);setMultiplier(1);}
 return <div className="program-explorer" data-testid="workflow-evidence"><div className="explorer-heading"><div><p className="eyebrow">WORKFLOW EVIDENCE EXPLORER</p><h3>Where does a forecast help the review queue?</h3></div><button className="catalog-reset" type="button" onClick={reset}>Reset workflow comparison</button></div><p>Explore saved December results. Stage and prefix filters change the evaluated cohort; no control refits a model or simulates new applications.</p>
 <div className="program-controls"><label>Workflow model<select value={model} onChange={e=>setModel(e.target.value)}>{models.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label><label>Observed event prefix<select value={prefix} onChange={e=>{setPrefix(Number(e.target.value));setStage("all");}}>{[5,10,20].map(x=><option key={x} value={x}>First {x} events</option>)}</select></label><label>Current application stage<select value={stage} onChange={e=>setStage(e.target.value)}>{stages.map(x=><option key={x} value={x}>{x==="all"?"All eligible stages":clean(x)}</option>)}</select></label></div>
 <div aria-live="polite"><div className="executive-stats"><div><strong>{row.mean_predicted_restricted_days.toFixed(2)}</strong><span>mean forecast remaining days</span></div><div><strong>{row.mean_observed_restricted_days.toFixed(2)}</strong><span>mean observed remaining days</span></div><div><strong>{row.mae_days.toFixed(2)}</strong><span>mean absolute error, days</span></div></div><p>{row.applications.toLocaleString("en-US")} applications · {row.prefixes.toLocaleString("en-US")} prefixes in this selection. Nominal 80% band coverage: {pct(row.coverage_80)}.</p><p className="caption">Average individual 80% prediction-band endpoints: {row.mean_lower_days.toFixed(2)}–{row.mean_upper_days.toFixed(2)} days. These averages are neither an interval for the group mean nor a guarantee for a particular application. Times are capped at 30 days. Subsets retain application-prefix weights; cells below 30 prefixes are unavailable.</p></div>
 <h4>Observed application-stage transitions</h4><p>Each card is a recorded link in the process. Select an available destination stage to inspect its forecasts above. The map uses the longest eligible prefix per application, independently of the filters.</p><div className="workflow-map" aria-label="Observed workflow transition map">{transitions.map(x=><div className="workflow-edge" key={`${x.from}-${x.to}`}><span>{clean(x.from)} →</span><button type="button" aria-pressed={stage===x.to} disabled={!stages.includes(x.to)} onClick={()=>setStage(x.to)}>{clean(x.to)}</button><strong>{x.median_elapsed_days<.01?"<0.01":x.median_elapsed_days.toFixed(2)} days</strong><span>median elapsed · {x.observations.toLocaleString("en-US")} transitions</span><span>90th percentile: {x.p90_elapsed_days<.01?"<0.01":x.p90_elapsed_days.toFixed(2)} days</span></div>)}</div><p className="caption">Edges with fewer than 30 observations are omitted. Disabled destinations lack an eligible diagnostic cell at this prefix. Elapsed time is not active work time; early prefixes omit later loops.</p>
 <h4>Prioritize late applications at a fixed review capacity</h4><p>This comparison includes all stages at the selected prefix. “Late” means no target status within 14 days after that prefix. Stage filtering above does not change these capacity totals.</p><div className="program-controls"><label>Review capacity<select value={capacity} onChange={e=>setCapacity(Number(e.target.value))}>{[.1,.2,.3,.5,1].map(x=><option key={x} value={x}>{100*x}% of applications</option>)}</select></label></div><p className="scenario-value" aria-live="polite">{late.late_selected} of {late.late_applications}<span>late applications identified among {late.selected} prioritized applications</span></p><p>Late-case capture: {pct(late.capture)}; conditional 95% interval {pct(late.capture_interval.lower)}–{pct(late.capture_interval.upper)}. This measures identification, not improvement caused by review.</p>
 <figure className="capacity-chart inventory-chart" tabIndex={0}><svg viewBox="0 0 660 320" role="img" aria-labelledby="workflow-chart-title workflow-chart-description"><title id="workflow-chart-title">Late-case capture by review capacity</title><desc id="workflow-chart-description">Selected model and conditional 95% interval compared with the stage and age baseline. Exact values for all models appear in the following table.</desc>{[0,.25,.5,.75,1].map(x=><g key={x}><line x1="70" x2="610" y1={py(x)} y2={py(x)} className="chart-grid"/><text x="60" y={py(x)+4} textAnchor="end">{100*x}%</text><text x={px(x)} y="285" textAnchor="middle">{100*x}%</text></g>)}<polygon points={band} fill="#925322" opacity=".12"/><polyline points={line(baseline)} stroke="#0a192f" fill="none" strokeWidth="2"/><polyline points={line(selected)} className="chart-policy"/><circle cx={px(capacity)} cy={py(late.capture)} r="6" className="chart-selected"/><text x="70" y="24">Share of late applications identified (%)</text><text x="340" y="314" textAnchor="middle">Review capacity (%)</text></svg><figcaption>Copper: selected model and conditional 95% band. Navy: stage/age baseline. Intervals retain the frozen rankings and are not simultaneous across capacities. Scroll horizontally on narrow screens.</figcaption></figure>
 <div className="program-table-wrap" tabIndex={0} role="region" aria-label="Workflow models at selected capacity"><table><caption>Event {prefix} · {100*capacity}% capacity · all eligible stages</caption><thead><tr><th scope="col">Model</th><th scope="col">Late identified</th><th scope="col">Capture</th><th scope="col">95% interval</th></tr></thead><tbody>{frontier.filter(x=>x.prefix===prefix&&x.capacity===capacity).map(x=><tr key={x.model}><th scope="row">{models.find(m=>m.id===x.model)!.label}</th><td>{x.late_selected} / {x.late_applications}</td><td>{pct(x.capture)}</td><td>{pct(x.capture_interval.lower)}–{pct(x.capture_interval.upper)}</td></tr>)}</tbody></table></div>
 <div className="scenario-panel"><p className="eyebrow">ASSUMED CAPACITY / SCENARIO ONLY</p><h3>Separate a staffing assumption from measured evidence.</h3><p>Assume some share of the selected cohort’s forecast duration varies inversely with capacity. The dataset does not identify that share or the effect of staffing.</p><div className="program-controls"><label>Assumed addressable share: {Math.round(share*100)}%<input aria-label="Assumed addressable share" type="range" min="0" max="1" step="0.05" value={share} aria-valuetext={`${Math.round(share*100)}% of forecast duration`} onChange={e=>setShare(Number(e.target.value))}/><span className="caption">0–100%; an assumption, not an estimated parameter.</span></label><label>Assumed capacity multiplier: {multiplier.toFixed(1)}×<input aria-label="Assumed capacity multiplier" type="range" min="0.5" max="2" step="0.1" value={multiplier} aria-valuetext={`${multiplier.toFixed(1)} times existing capacity`} onChange={e=>setMultiplier(Number(e.target.value))}/><span className="caption">0.5–2.0× existing capacity.</span></label></div><p className="scenario-value" aria-live="polite">{(row.mean_predicted_restricted_days*factor).toFixed(2)} days<span>hypothetical duration versus {row.mean_predicted_restricted_days.toFixed(2)} forecast days</span></p><p className="caption">Formula: forecast × [(1 − share) + share ÷ multiplier]. No causal confidence interval is available. Values above 30 days extrapolate beyond the fitted horizon. These assumptions do not alter observed error, measured coverage or the review comparison.</p></div></div>;
}
