import type { Metadata } from "next";
import Link from "next/link";
export const metadata: Metadata = { title: "Terms & Disclosures", description: "The scope, limitations and third-party rights of this independent professional portfolio.", alternates: { canonical: "/terms" } };
export default function Terms() {
  return <main id="main" tabIndex={-1} className="shell legal-page"><Link className="back-link" href="/">← Home</Link><p className="eyebrow">TERMS &amp; DISCLOSURES</p><h1>Context for the work.</h1><p className="legal-intro">This is an independent professional portfolio of Michael P. Gibb, Ph.D.</p>
    <section><h2>Research and demonstrations</h2><p>Public-data studies and synthetic demonstrations are labeled separately. Planned and developing topics do not represent completed research. Portfolio findings are independent analytical work and do not represent client engagements or delivered client outcomes unless explicitly identified.</p><p>Study results apply to the stated data, evaluation design and limitations. Scenario controls illustrate assumptions, not guaranteed outcomes. Historical associations and predictive accuracy do not by themselves establish causal effects or future business returns. Study-specific limitations remain alongside the findings.</p></section>
    <section><h2>Professional context</h2><p>The material is provided to explain analytical methods, judgment and professional interests. It does not establish a professional engagement or provide individualized financial, legal, medical or other regulated advice. Contact inquiries can begin a discussion about scope and suitability.</p><p>References to organizations, datasets, products or institutions do not imply sponsorship or endorsement.</p></section>
    <section><h2>Rights and attribution</h2><p>Third-party datasets, software and other materials retain their respective rights and licenses. Follow the citations, source links and license notices accompanying each study or download before reusing material. A link to public material does not grant additional rights.</p><p>The skyline artwork is a stylized Chicago-inspired brand mark. It is not a geographically exact skyline or an architectural survey.</p></section>
    <section><h2>Questions or corrections</h2><p>Use the <Link href="/#contact">contact form</Link> to raise a question about this portfolio, report a correction or discuss appropriate reuse. See <Link href="/privacy">Privacy</Link> for how inquiry information is handled.</p></section>
  </main>;
}
