import { z } from "zod";
import catalog from "../program-catalog.json" with { type: "json" };
import completed from "../completed-studies.json" with { type: "json" };
export const publicProjects = [ ...catalog.filter(s => s.publicationStatus !== "withheld" && s.publicationStatus !== "draft").map(s => ({ id: s.id, title: s.title, path: s.publicationStatus === "published" ? `/research/${s.slug}` : `/research`, status: s.publicationStatus === "published" ? "Evaluated study" : "Planned research" })), { id: "marketing-incrementality", title: "Marketing effectiveness and incrementality", path: "/projects/marketing-incrementality", status: "Synthetic demonstration" }, ...completed.map(s => ({ id: s.slug, title: s.title, path: `/projects/${s.slug}`, status: "Synthetic demonstration" })) ];
export const projectId = z.string().refine(id => publicProjects.some(p => p.id === id));
const paths = new Set(["/", "/research", "/privacy", "/terms", ...publicProjects.map(p => p.path)]);
export const canonicalPath = (input: string) => { try { const path = new URL(input, "https://michaelpgibb.com").pathname.replace(/\/$/, "") || "/"; return paths.has(path) ? path : "/unknown"; } catch { return "/unknown"; } };
export const events = ["page_view", "page_exit", "active_reading", "section_view", "scroll_depth", "navigation", "menu", "search", "filter", "research_result", "project_view", "download_click", "source_click", "demo_start", "demo_change", "demo_run", "demo_reset", "demo_error", "assistant_open", "assistant_close", "conversation_start", "message_submit", "response_complete", "response_failed", "response_cancelled", "assistant_source", "assistant_recommendation", "assistant_feedback", "contact_handoff", "contact_view", "contact_start", "contact_validation", "contact_attempt", "inquiry_received", "provider_accepted", "email_delivered", "email_bounced", "contact_failed", "consent_change", "page_performance", "application_error"] as const;
export const serverEvents = new Set(["conversation_start", "response_complete", "response_failed", "response_cancelled", "inquiry_received", "provider_accepted", "email_delivered", "email_bounced", "contact_failed"]);
export const intentSchema = z.enum(["marketing", "forecasting", "customer", "operations", "methods", "career", "contact", "other"]);
export function intentOf(query: string): z.infer<typeof intentSchema> { for (const [intent, re] of Object.entries({ marketing: /market|campaign|advertis|increment/, forecasting: /forecast|sales|revenue|demand/, customer: /customer|churn|retention|loyal/, operations: /inventor|operat|supply|capacity/, methods: /causal|regression|model|method|statistic/, career: /career|experience|bio|leadership|qualification/, contact: /contact|hire|consult|collaborat/ })) if (re.test(query.toLowerCase())) return intent as z.infer<typeof intentSchema>; return "other"; }
export const propertiesSchema = z.object({
  industry: z.string().refine(v => catalog.some(s => s.industry === v)).optional(), method: z.string().refine(v => catalog.some(s => s.methods.includes(v))).optional(), country: z.string().regex(/^[A-Z]{2}$/).optional(),
  project_id: projectId.optional(), position: z.number().int().min(1).max(100).optional(), count: z.number().int().min(0).max(100).optional(),
  intent: intentSchema.optional(), category: z.enum(["open", "close", "select", "industry", "method", "status", "area", "decision", "clear", "positive", "negative", "executive", "technical", "ordinary", "assistant", "unknown", "timeout", "provider", "cancelled", "rate_limit", "invalid", "unavailable", "empty", "success", "link", "download", "source", "parameter", "navigation", "layout", "performance"]).optional(),
  seconds: z.number().int().min(0).max(300).optional(), percent: z.union([z.literal(25), z.literal(50), z.literal(75), z.literal(100)]).optional(),
  target: z.string().refine(v => canonicalPath(v) === v || ["github", "linkedin", "external", "download"].includes(v)).optional(),
  section: z.enum(["hero", "work", "approach", "about", "contact", "executive", "decision", "evidence", "data", "method", "limitations", "code", "other"]).optional(),
  latency_ms: z.number().min(0).max(120000).optional(), tokens: z.number().int().min(0).max(30000).optional(), cost_usd: z.number().min(0).max(1).optional(), model: z.enum(["gpt-5-mini"]).optional(), model_version: z.string().regex(/^gpt-5-mini(?:-\d{4}-\d{2}-\d{2})?$/).optional(),
  inquiry_id: z.string().uuid().optional(), conversation_id: z.string().uuid().optional(), analytics: z.boolean().optional(), replay: z.boolean().optional(), version: z.literal(1).optional(),
}).strict();
export const eventSchema = z.object({ id: z.string().uuid(), name: z.enum(events), path: z.string().refine(p => canonicalPath(p) === p && p !== "/unknown"), component: z.enum(["page", "header", "footer", "research", "study", "demo", "assistant", "contact", "preferences", "server"]), properties: propertiesSchema, time: z.string().datetime() }).strict();
export type Event = z.infer<typeof eventSchema>;
export type Properties = z.infer<typeof propertiesSchema>;
export const attributionSchema = z.object({ source: z.enum(["direct", "linkedin", "github", "google", "bing", "other"]), campaign: z.enum(["none", "linkedin-profile", "portfolio-share", "research-release", "other"]), device: z.enum(["mobile", "tablet", "desktop"]), browser: z.enum(["safari", "firefox", "edge", "chrome", "other"]), returning: z.boolean() }).strict();
export type Attribution = z.infer<typeof attributionSchema>;
