"use client";
import { useEffect, useRef, useState, type FormEvent } from "react";
import Link from "next/link";
import { ContactForm } from "@/components/contact-form";
import { TurnstileVerification, type VerificationHandle } from "@/components/turnstile-verification";
import { track } from "@/lib/experience/analytics-client";
import { intentOf, publicProjects } from "@/lib/experience/schema";
import type { Source } from "@/lib/experience/retrieval";
import type { ContactFields } from "@/lib/contact-validation";
export function AssistantPanel({ projectId, onClose }: { projectId?: string; onClose: () => void }) {
  const dialog = useRef<HTMLDialogElement>(null); const verification = useRef<VerificationHandle>(null); const controller = useRef<AbortController | null>(null); const session = useRef(0); const transcript = useRef<HTMLDivElement>(null);
  const [tab, setTab] = useState<"chat" | "contact">("chat"); const [mode, setMode] = useState<"executive" | "technical">("executive"); const [draft, setDraft] = useState(""); const [busy, setBusy] = useState(false); const [available, setAvailable] = useState(false); const [contact, setContact] = useState(false); const [notice, setNotice] = useState("Checking availability…");
  const [messages, setMessages] = useState<{ role: "visitor" | "assistant"; text: string; sources?: Omit<Source,"excerpt">[] }[]>([]); const [recommended, setRecommended] = useState<string[]>(projectId ? [projectId] : []);
  const study = publicProjects.find(p => p.id === projectId);
  useEffect(() => {
    const previous = document.activeElement as HTMLElement | null; const overflow = document.body.style.overflow; document.body.style.overflow = "hidden"; dialog.current?.showModal(); track("assistant_open", "assistant", { project_id: projectId });
    let mounted = true; void fetch("/api/assistant/config", { cache: "no-store" }).then(r => r.json()).then(data => { if (mounted) { setAvailable(data.available); setContact(data.contact); setNotice(data.available ? "" : "AI answers are awaiting activation. You can explore the catalogue or prepare an inquiry below."); } }).catch(() => { if (mounted) setNotice("The assistant is unavailable. The research catalogue and ordinary contact form remain available."); });
    return () => { mounted = false; controller.current?.abort(); document.body.style.overflow = overflow; previous?.focus(); track("assistant_close", "assistant", { project_id: projectId }); };
  }, [projectId]);
  useEffect(() => { transcript.current?.scrollTo({ top: transcript.current.scrollHeight, behavior: "instant" }); }, [messages]);
  function close() { controller.current?.abort(); onClose(); }
  async function submit(event: FormEvent) {
    event.preventDefault(); if (busy || !draft.trim() || !available) return; const message = draft.trim(); const abort = new AbortController(); controller.current = abort; setBusy(true); setNotice("");
    try {
      if (session.current < Date.now()) {
        setNotice("Verifying before starting your conversation…"); const token = await Promise.race([verification.current?.verify(), new Promise<never>((_, reject) => abort.signal.addEventListener("abort", () => reject(new Error("cancelled")), { once:true }))]); if (!token || abort.signal.aborted) throw new Error("cancelled");
        const response = await fetch("/api/assistant/session", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ turnstileToken: token }), signal: abort.signal }); const data = await response.json(); if (!response.ok) throw new Error(data.error); session.current = Date.now() + (data.expiresIn - 5) * 1000;
      }
      setNotice("Finding relevant evidence…"); track("message_submit", "assistant", { project_id: projectId, intent: intentOf(message), category: mode });
      const response = await fetch("/api/assistant/message", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ requestId: crypto.randomUUID(), message, projectId, mode }), signal: abort.signal });
      if (!response.ok || !response.body) { const error = await response.json(); if (error.verificationRequired) session.current = 0; throw new Error(error.error ?? "The assistant could not respond. Please retry."); }
      setMessages(previous => [...previous, { role: "visitor", text: message }, { role: "assistant", text: "", sources: [] }]);
      const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = ""; let complete = false;
      while (true) { const { value, done } = await reader.read(); if (done) break; buffer += decoder.decode(value, { stream:true }); let end;
        while ((end = buffer.indexOf("\n\n")) !== -1) { const frame = buffer.slice(0,end); buffer = buffer.slice(end+2); const type = frame.match(/^event: (.*)/m)?.[1]; const data = JSON.parse(frame.match(/^data: (.*)/m)?.[1] ?? "{}");
          if (type === "delta") { setNotice(""); setMessages(previous => previous.map((m,i) => i === previous.length-1 ? { ...m, text: m.text + data.text } : m)); }
          if (type === "sources") { setRecommended(data.map((s: Source) => s.id).filter((id: string) => publicProjects.some(p => p.id === id)).slice(0,5)); setMessages(previous => previous.map((m,i) => i === previous.length-1 ? { ...m, sources:data } : m)); }
          if (type === "done") complete = true;
          if (type === "error") throw new Error(data.error);
        }
      }
      if (!complete) throw new Error("The response ended early. Your message is still here; please retry."); setDraft(""); setNotice("");
    } catch (error) { setNotice(abort.signal.aborted ? "Response stopped. Your message is still here." : error instanceof Error ? error.message : "The response failed. Please retry."); } finally { setBusy(false); controller.current = null; }
  }
  return <dialog ref={dialog} className="experience-dialog assistant-panel" aria-labelledby="assistant-title" onCancel={close}><div className="assistant-top"><div><p className="eyebrow">PORTFOLIO RESEARCH</p><h2 id="assistant-title">Ask about my work</h2><p>AI assistant · Not Michael or a live representative</p></div><button type="button" onClick={close} aria-label="Close assistant">×</button></div><div className="assistant-body">
    <div className="assistant-actions"><button onClick={() => { setTab("chat"); setDraft("Help me find research about "); }}>Find relevant research</button><button onClick={() => { setTab("chat"); setDraft(study ? `Explain ${study.title}, its findings and limitations.` : "Which study should I explore for my business problem? "); }}>Explain {study ? "this project" : "a project"}</button><button onClick={() => { setTab("contact"); track("contact_handoff", "assistant", { project_id: projectId }); }}>Contact Michael</button></div>
    {study && <p className="assistant-context">Context: {study.title} · {study.status}</p>}
    {tab === "chat" ? <><div className="assistant-transcript" ref={transcript} aria-label="Conversation">{messages.length === 0 && <p>Explore published findings, methods and limitations. Share a business problem to find related work. Please keep confidential information out of chat.</p>}{messages.map((message,i) => <article key={i} className={`assistant-message ${message.role}`}><strong>{message.role === "visitor" ? "You" : "AI assistant"}</strong><p>{message.text || "Preparing a response…"}</p>{message.sources?.map(source => <a key={source.id} className="assistant-source-card" href={source.url} onClick={() => { const id = publicProjects.some(p => p.id === source.id) ? source.id : undefined; track("assistant_source", "assistant", { project_id: id }); if (id) track("assistant_recommendation", "assistant", { project_id: id }); }}><strong>{source.title}</strong><span>{source.status} · View evidence ↗</span></a>)}{message.role === "assistant" && message.text && <div className="assistant-feedback"><span>Was this helpful?</span><button onClick={() => track("assistant_feedback", "assistant", { category:"positive" })}>Yes</button><button onClick={() => track("assistant_feedback", "assistant", { category:"negative" })}>No</button></div>}</article>)}</div><form className="assistant-compose" onSubmit={submit}><label htmlFor="assistant-mode">Explanation style<select id="assistant-mode" value={mode} onChange={e => setMode(e.target.value as typeof mode)} disabled={busy}><option value="executive">Executive · decisions and implications</option><option value="technical">Technical · methods and assumptions</option></select></label><label htmlFor="assistant-question">Your question<textarea id="assistant-question" maxLength={2000} rows={3} value={draft} onChange={e => setDraft(e.target.value)} placeholder="What business problem are you exploring?" /></label><TurnstileVerification ref={verification} action="chat_init" compact /><div className="experience-actions"><button type="submit" disabled={!available || busy || !draft.trim()}>Ask assistant</button>{busy && <button type="button" onClick={() => controller.current?.abort()}>Stop response</button>}<Link href="/research" onClick={close}>Explore all research</Link></div></form></> : <AssistedInquiry available={contact} projects={recommended} />}
    <p className="assistant-status" role="status" aria-live="polite">{notice}</p><p className="assistant-disclaimer">Answers can be mistaken; consult the linked evidence. Chat context expires within 15 minutes. Only an inquiry you review and send is delivered. <Link href="/privacy">Privacy</Link></p>
  </div></dialog>;
}
function AssistedInquiry({ available, projects }: { available: boolean; projects: string[] }) {
  const [type, setType] = useState<ContactFields["topic"]>("Other"); const [role, setRole] = useState(""); const [timeline, setTimeline] = useState(""); const [challenge, setChallenge] = useState(""); const [selected, setSelected] = useState(projects); const [draft, setDraft] = useState<ContactFields | null>(null);
  return <section className="assisted-inquiry"><h3>Prepare an inquiry</h3><p>Your chat is not attached. Review and edit the entire message before sending.</p>{!draft ? <form className="assistant-compose" onSubmit={e => { e.preventDefault(); setDraft({ name:"", email:"", company:"", phone:"", topic:type, message:[challenge, role ? `Role: ${role}` : "", timeline ? `Timeline: ${timeline}` : "", ...selected.map(id => { const p = publicProjects.find(p => p.id === id); return p ? `Related work: ${p.title} — https://michaelpgibb.com${p.status === "Planned research" ? `/research?status=agenda#topic-${p.id}` : p.path}` : ""; })].filter(Boolean).join("\n\n") }); }}><label>Inquiry type<select value={type} onChange={e => setType(e.target.value as ContactFields["topic"])}><option value="Leadership opportunity">Hiring</option><option value="Analytics or AI project">Consulting</option><option value="Research collaboration">Research collaboration</option><option value="Other">General question</option></select></label><label>What would you like to discuss?<textarea required minLength={10} maxLength={3500} value={challenge} onChange={e => setChallenge(e.target.value)} rows={4} /></label><label>Your role (optional)<input value={role} maxLength={100} onChange={e => setRole(e.target.value)} /></label><label>Timeline (optional)<input value={timeline} maxLength={150} onChange={e => setTimeline(e.target.value)} /></label>{projects.length > 0 && <fieldset><legend>Include these project links (optional)</legend>{projects.map(id => <label key={id}><input type="checkbox" checked={selected.includes(id)} onChange={e => setSelected(ids => e.target.checked ? [...ids,id] : ids.filter(v => v !== id))} />{publicProjects.find(p => p.id === id)?.title}</label>)}</fieldset>}<button type="submit">Review editable inquiry</button></form> : <div className="inquiry-preview"><h4>Your complete inquiry</h4><p>Add your contact details, then edit the message below. Sending requires a fresh security verification.</p><ContactForm available={available} initialValues={draft} origin="assistant" projects={selected} /><button onClick={() => setDraft(null)}>Back to draft details</button></div>}</section>;
}
