"use client";
import { useEffect, useState } from "react";
import type { Inquiry } from "@/lib/experience/inquiries";
export function OwnerInbox() {
  const [offset, setOffset] = useState(0);
  const [rows, setRows] = useState<Inquiry[]>([]); const [notice, setNotice] = useState("Loading inbox…");
  async function load(nextOffset = offset) { try { const response = await fetch(`/api/owner/inquiries?offset=${nextOffset}`, { cache: "no-store" }); if (!response.ok) throw new Error(); const data = await response.json(); setRows(data.inquiries); setOffset(nextOffset); setNotice(""); } catch { setNotice("Inbox unavailable. Sign in again or retry."); } }
  useEffect(() => { document.cookie = "portfolio-owner-exclude=1; Path=/; Secure; SameSite=Lax; Max-Age=31536000"; void fetch("/api/owner/inquiries", { cache: "no-store" }).then(async response => { if (!response.ok) throw new Error(); const data = await response.json(); setRows(data.inquiries); setNotice(""); }).catch(() => setNotice("Inbox unavailable. Sign in again or retry.")); }, []);
  const accepted = rows.filter(r => r.status?.provider_accepted).length;
  return <div className="owner-inbox"><p>Current page of up to 50 retained inquiries · Times: America/Chicago. Application receipt: {rows.length}; provider accepted: {accepted}; consented journeys: {rows.filter(r => r.consent?.analytics).length}. Analytics totals can be lower because of consent, blocking, limits, or delivery failures.</p><p><a href="https://us.posthog.com/" target="_blank" rel="noreferrer">Open authenticated PostHog dashboards ↗</a> · <a href="/api/owner/inquiries" download="portfolio-inquiries.json">Export this inquiry page</a> · <a href="/api/owner/operations">View essential aggregate AI operations</a></p><button onClick={() => void load()}>Refresh inbox</button> <button disabled={offset === 0} onClick={() => void load(Math.max(0,offset-50))}>Newer inquiries</button> <button disabled={rows.length < 50} onClick={() => void load(offset+50)}>Older inquiries</button><p role="status">{notice}</p>{rows.map(row => <details key={row.id}><summary>{new Date(row.created).toLocaleString("en-US", { timeZone: "America/Chicago" })} · {row.fields.name} · {row.origin} · {row.status?.email_bounced ? "Bounced" : row.status?.email_delivered ? "Delivered to mail server" : row.status?.provider_accepted ? "Provider accepted" : "Application received"}</summary><p>{row.fields.email} · {row.fields.company} · {row.fields.phone}</p><pre>{row.fields.message}</pre><p>Projects: {row.projects.join(", ") || "None supplied"}. Attribution: {row.consent?.attribution ? `${row.consent.attribution.source} / ${row.consent.attribution.campaign}` : "Unknown (no retained consented attribution)"}.</p><details><summary>Consented journey and delivery timestamps</summary><pre>{JSON.stringify({ journey: row.journey, status: row.status }, null, 2)}</pre></details><p>Expires {new Date(row.expires).toLocaleDateString("en-US", { timeZone: "America/Chicago" })}. Deletion also removes linked local journey records; retained mailbox correspondence needs separate review.</p><button onClick={async () => { if (!window.confirm("Delete this inquiry and its linked retained local journey?")) return; const result = await fetch(`/api/owner/inquiries/${row.id}`, { method: "DELETE" }); if (result.ok) { const data = await result.json(); await load(); setNotice(data.note); } else setNotice((await result.json()).error ?? "Deletion unavailable."); }}>Delete inquiry and linked records</button></details>)}</div>;
}
